In [3]:
import numpy as np  # numpy 패키지 가져오기
import pandas as pd # pandas 패키지 가져오기
import matplotlib.pyplot as plt # 시각화 패키지 가져오기
import seaborn as sns # 시각화

## 2.데이터 전처리
import re                             # 정규식 모듈 임포트

## 3.형태소 처리
from konlpy.tag import Okt
import nltk
from collections import Counter

In [6]:
a_df = pd.read_csv('C:/한화에어로스페이스/workspaces/Crawling project/theBoram4Jo/data/방위사업청_국내조달 경쟁 입찰결과_20241031.csv', encoding="cp949")
a_df.head()

,입찰공고번호,입찰공고차수,입찰공고명,업무구분명,계약체결형태명,계약체결방법명,낙찰자결정방법명,적격심사여부,공고기관명,공고기관코드,...,개찰시각,개찰결과구분명,최종낙찰금액,최종낙찰율,최종낙찰일자,최종낙찰업체명,최종낙찰업체대표자명,최종낙찰업체담당자명,최종낙찰업체사업자등록번호,최종낙찰업체주소
0,MHD0102,4,상륙기동헬기 조종시뮬레이터 선행연구,용역,총액계약,협상에의한계약(서류),협상,N,방위사업청(운영지원과),1690000,...,14:00:00,개찰완료,28000000.0,93.333,2016-02-11,재단법인 한국군사문제연구원,김형철,NaN,126-82-20298,"경기도 성남시 수정구 위례대로83(창곡동, 국방문화센터)"
1,MHD0130,2,특수작전용 유탄발사기사업 선행연구,용역,총액계약,협상에의한계약(서류),협상,N,방위사업청(운영지원과),1690000,...,14:00:00,개찰완료,71000000.0,95.826,2016-01-06,사단법인 안보경영연구원,전건욱,NaN,120-82-07415,"서울특별시 강남구 언주로527, 10층 (역삼동)"
2,UMM0003,2,00부대 물절약 투자대행사업(WASCO 15-A047),용역,총액계약,협상에의한계약(전자),협상,N,국군재정관리단,ZD00303,...,11:00:00,개찰완료,535467000.0,80.279,2016-01-29,주식회사 도화엔지니어링,손영일,유근영,211-81-08009,서울특별시 강남구 삼성로 438(대치동)
3,UMM0004,2,00부대 물절약 투자대행사업(WASCO 15-A048),물품,총액계약,협상에의한계약(전자),협상,N,국군재정관리단,ZD00303,...,11:00:00,유찰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UMM0860,2,16년 음향 영상장비 유지보수 용역,용역,총액계약,일반경쟁,적격심사제,Y,국군재정관리단,ZD00303,...,11:00:00,개찰완료,396923000.0,86.972,2016-01-05,주식회사 케이원,송관섭,전대석,107-81-54150,"서울특별시 금천구 가산디지털2로14, 14층 1405, 1406호(가산동)"

In [7]:
a_df = a_df[a_df['업무구분명'] != '용역']

In [17]:
a_df.업무구분명

3        물품
9        물품
10       물품
11       물품
13       물품
         ..
74673    물품
74674    물품
74675    물품
74676    물품
74677    물품
Name: 업무구분명, Length: 61432, dtype: object

In [23]:
a_list = []

for i in range(len(a_df)):
    text = a_df['입찰공고명'].iloc[i]
    a_list.append(text)
a_list

['00부대 물절약 투자대행사업(WASCO  15-A048)',
 '155밀리 모의신관류',
 '155밀리 모의신관류',
 '155밀리 모의신관류',
 '스펙트럼용 분석기 구매',
 '16년 대전병원 장비운영유지비(외과장비3) 구매',
 '16년 대전병원 장비운영유지비(외과장비1) 구매',
 '팥빙수 구매',
 '바나나우유 구매',
 '콜라 구매',
 '과일탄산 구매',
 '16년 대전병원 장비운영유지비(영상장비) 구매',
 '16년 대전병원 장비운영유지비(영상장비) 구매',
 '혼합음료 구매',
 '탄산수 구매',
 '이온음료 구매',
 '알로에음료 구매',
 '마시는발효유 구매',
 '떠먹는발효유 구매',
 '짜먹는발효유 구매',
 '떠먹는 젤리 구매',
 '한줌견과 구매',
 '특근자용 치즈케이크(제조)',
 '특근자용 치즈케이크(제조)',
 '콘브레드(제조)',
 '콘브레드(제조)',
 '짜장컵밥 구매',
 '허니감자스낵 구매',
 '해상사격표적(풍선 등 2종) 구매',
 '넬라톤카테터 등 234품목 구매(물품)',
 '신병증식용 치즈케이크 구매(제조)',
 '신병증식용 치즈케이크 구매(제조)',
 '탄산음료 구매',
 '신병증식용 핫바 구매',
 '13-본-국대-01 00학교이전 공기조화기 제조설치',
 '13-본-국대-01 00학교이전 PE전선관 등 2종 제조',
 '충전기집적회로등17종구매',
 'D형들고리등13종구매',
 '락카스프레이황색등24종구매',
 '16-1차 전산운영용품 구매',
 '보장구 80종 구매',
 '크림빵 구매(제조)',
 '크림빵 구매(제조)',
 '크림빵 구매(제조)',
 '크림빵 구매(제조)',
 '컨테이너 2종 제조 설치',
 '미세먼지 방지마스크 구매',
 '스위치  칼날형 등 9품목',
 'K1채널씰등12종구매',
 'K1베어링등11종구매',
 'K1베어링등11종구매',
 '자주발칸 케이블조립체등2종구매',
 '자주발칸 케이블조립체등2종구매',
 'K1링등29종구매',
 'K1링등29종구매',
 '핫바 구매',
 '16년 증식용 떡 및 케이크 구매',
 '1분기 식품검사 재료 구매',
 '액화석유가스(LPG) 공급',
 '조리병교육대 교육 재료',
 '대전병원 병리재료 소모품 67종 구매',
 '16-014 쉽게 생각하고 쉽게 배우는 수영 등 143종',
 '대전병원 외과장비 소모품 5종 구매',
 '대전병원 보장구 50종 구매',
 '아산화질소 1항목 구매(물품)',
 '아산화질소 1항목 구매(물품)',
 '세척재료(세척제  용제) 구매',
 '취사용 LPG 구매',
 '더블에이 복사용지 등 243품목',
 '버니어 켈리퍼스  등 174품목',
 '00부대(6진) 정비반 물품 구매(1차)',
 '00부대(6진) 정기재보급 물품 구매(1차)',
 '손목시계 제조납품',
 '접착제등55종구매',
 '디지털 인쇄재료 38종 구매',
 '대구병원 공조기필터 교체 설치납품',
 '인쇄용지 3종 구매',
 '부산병원 공조기필터 교체 설치납품',
 '16- 백령도 빵류 납품',
 '교육용 패킷 분석장비 라이선스 구매',
 '의료재료 395종 구매',
 '00부대 간부식당 식자재 구매(육류)',
 '북한 및 해외 간행물 구매',
 '북한 및 해외 간행물 구매',
 '온도센서 등 32종 구매',
 '16년 오리콘용 탄약장진기',
 '육군 간부수첩 표지 제조',
 '의무장비 운영소모품 166종 구매',
 '병리장비 운영소모품 84종 구매',
 '병리장비 운영소모품 62종 구매',
 '병리장비 운영소모품 43종 구매',
 '외과장비 운영소모품 61종 구매',
 '외과장비 운영소모품 29종 구매',
 '외과장비 운영소모품 72종 구매',
 '방사선장비 운영소모품 13종 구매',
 '특수수술재료(반월상연골봉합술재료 등 3건) 구매',
 '병리장비 운영소모품 47종 구매',
 '소시지',
 '어묵(용기)',
 '16년 LPG 구매(경기북부)',
 '16년 LPG 구매(경기남부)',
 '16년 LPG 구매(서울)',
 '16년 LPG 구매(인천)',
 '16년 LPG 구매(인천)',
 '16-F-013 윈치 등 11종 구매',
 '병리장비 운영소모품 60종 구매',
 '특수수술재료(수술 후 유착방지용 등 3건) 구매',
 '핸드맥스 등 521품목 구매',
 '멀티탭 등 235품목',
 '내향성발톱교정재료 구매',
 '병리재료 108종 구매',
 '치과재료 234종 구매',
 '표창장 표지 제조',
 'LPG 연차',
 '16-K-액화석유가스(LPG)(강화도서)',
 '마이크로폰  고성능식 3EA',
 '16년 대전병원 병 건강검진 재료 구매',
 '16년 대전병원 의료기재(치과재료) 구매',
 '16년 대전병원 기타의약품 구매',
 '16년 대전병원 핵의약품(체내검사용) 구매',
 '16년 대전병원 핵의약품(체내검사용) 구매',
 '16년 대전병원 핵의약품(체내검사용) 구매',
 '16년 대전병원 핵의학품(체외검사용) 구매',
 '16년 대전병원 핵의학품(체외검사용) 구매',
 '황산등59종구매',
 '16년 가스터빈엔진 정비',
 '16년 가스터빈엔진 정비',
 '바닥광택기',
 '소총용 어댑터류',
 '병기수지제품류',
 '병기수지제품류',
 '꼬질대류',
 '수입솔류',
 '00부대 간부식당 식자재 계약(농수산 가공품 등)',
 '정비피복(방진화) 구매',
 '분석기(회로망용) 구매',
 '16-K-액화석유가스(LPG)(소형저장탱크)',
 '16-K-액화석유가스(LPG)(인천/강화)',
 '16-K-액화석유가스(LPG)(김포)',
 '가지 등 306종 구매(추자도)',
 '감자 등 170종 구매(거문도)',
 '가지 등 181종 구매(안마도)',
 '16년 천마 응축기 조립체 정비',
 '1/4분기 교육/실습재료 구매',
 '마술용품 등 126종',
 '키보드 2단 스탠드 등 38종',
 '키보드 2단 스탠드 등 38종',
 '용접장갑 등 122품목',
 '시설대대 스틸그레이팅 등 27종(16-005)',
 '카트리지 필터 100개',
 '핫도그 등 50종 구매',
 '이온음료 등 4종 구매',
 '멸균흰우유 등 3종 구매',
 '분석기세트 3종 구매',
 '체육기구류(당구대 등 22종)설치 납품',
 '소석회살포기 5항목 구매(물자)',
 '25톤 덤프 육각 너트 등 126항목 구매(기장)',
 '로디우스 볼트 등 52항목 구매(기장)',
 '봉고 연료필터 등 42항목 구매(기장)',
 '국방 빅데이터 플랫폼 기반 구축사업 리스계약',
 '인쇄용지 2종 구매',
 'E/O Gas 카트리지 등 124종',
 '메탄올등19종구매',
 '실리콘등11종구매',
 '건조제등48종구매',
 '부분순간냉각제등19종구매',
 '부분순간냉각제등19종구매',
 '전도성접착제등3종구매',
 '전도성접착제등3종구매',
 '볼형손잡이 등 381종 구매',
 '훈련용 통신기 등 21종 구매',
 '포장두부 등 5종 구매',
 '냉동오리고기 등 5종 구매',
 '떡볶이 구매(구매 또는 제조)',
 '떡볶이 구매(구매 또는 제조)',
 'USB 684개',
 '핫바 구매',
 '스키드로더 후레쉬 에어필터 등 207항목 구매(기장)',
 '굴삭기 파이프 등 281항목 구매(기장)',
 '열화상카메라 등 2종 구매',
 '표면조도측정기 구매',
 '00부대(6진) 정비반 물품 구매(5차)',
 'PMS공정형 및 이동형 중계기 등 0종 제조 설치납품',
 '국군간호사관학교 교과서 35종 구매',
 '대전병원 병원장비 소모품 71종 구매',
 '00함 가스터빈 유압시동기 패널 정비',
 '대전병원 효소면역 측정기 소모품 33종 구매',
 '대전병원 자동 뇨 분석기 등 소모품 46종 구매',
 '대전병원 생화학 자동 분석기 소모품 20종 구매',
 '화강석(여장석) 4종 제조',
 '오렌지 등 9종 구매',
 '오렌지 등 9종 구매',
 '어묵탕(용기) 구매(구매 또는 제조)',
 '차량정비용(타이어/밧데리) 연간단가계약',
 '핫바',
 '쌈무',
 '깐메추리알',
 '포장순대',
 '단무지',
 '생우동',
 '단호박샐러드',
 '고구마샐러드',
 '메밀국수',
 '모짜렐라치즈',
 '슬라이스치즈',
 '스파게티면',
 '핫도그',
 '사과푸딩',
 '망고푸딩',
 '요거트푸딩',
 '국수',
 '콘푸라이트',
 '마카로니',
 '돈까스소스',
 '칠리소스',
 '데리야끼소스',
 '두반장소스',
 '스파게티소스',
 '캡사이신소스',
 '굴소스',
 '진간장',
 '초콜릿가공품',
 '카스타드',
 '마가렛트',
 '후레쉬베리',
 '초코파이',
 '초코바',
 '에너지바',
 '몽쉘',
 '콜라',
 '사이다',
 '매실음료',
 '포도맛음료',
 '오렌지맛음료',
 '식혜',
 '옥수수수염차',
 '바나나우유',
 '두유',
 '요구르트',
 '떠먹는요구르트',
 '복숭아아이스티',
 '코코넛음료',
 '매실농축액(매원)',
 '증식류 크림빵 구매',
 '증식류 피자빵 구매',
 '증식류 소시지빵 구매',
 '쇄석 등 293종',
 '증식류 치즈케익 구매',
 '증식류 치즈케익 구매',
 '증식류 초코머핀 구매',
 '증식류 견과류형 초코바 구매',
 '증식류 크런키형 초코바 구매',
 '증식류 용기떡볶이 구매',
 '증식류 용기순대 구매',
 '액화석유가스',
 'K277장갑차 발전기 보조엔진용 정비',
 'K277장갑차 발전기 보조엔진용 정비',
 '하이브리드 키폰 구매 설치',
 '00부대(6진) 정비반 물품 구매(3차)',
 '00부대(6진) 정비반 물품 구매(4차)',
 '16-백령도 도서전투부식 구매',
 '16-백령도 분식류 구매',
 '16-백령도 가공식품류 구매',
 '16-백령도 개선식 구매',
 '16-백령도 기호식품 구매',
 '16-대청도 부대조달부식 구매',
 '16-소청도 부대조달부식 구매',
 '16-백령도 두채류 구매',
 '16-백령도 김치류 납품',
 '감압밸브 등 69품목 구매',
 '6각 빗트 소켓 등 907종',
 '식품작업용그릇 등 8종 구매',
 '간부숙소 알루미늄창호 제조설치',
 '유해발굴 수습물자(관 등 4종) 제조납품',
 '유해발굴 수습물자(스폰지 등 15종) 구매납품',
 '증식류 소시지바 구매',
 '증식류 호떡 구매',
 '치과용 캐비닛 1항목 구매 설치(물품)',
 '수술용 칼 5항목 구매(물품)',
 '이마형 체온계 등 7항목  구매(물품)',
 '흑구습구온도계 등 4항목 구매(물품)',
 '포제명찰 새김 및 벨크로 부착 제조',
 '뉴PD수첩 등 363종',
 '00부대 육아보육시설 교재교구류 구매',
 'PC-132A 건전지 등 9항목 구매(물자)',
 'LBP-6535K 토너/드럼(슈퍼재생) 등 7항목 제조',
 'HP-CLJ5550DN 검정(정품) 등 70항목 구매',
 '밸브  솔레노이드용 등 22품목',
 '부품키트  스로틀  조절레버용 등 17품목',
 '워터젯추진기용 실린더',
 '케이블조립체(TPQ-36 37용)',
 '케이블조립체(TAS-970K용)',
 '볼펜 등 438품목 구매',
 '에프시 듀라토프 디피 등 20품목',
 '지뢰제거작전 보호의 등 장비구매',
 '수도병원 보장구 72종 구매',
 '파병 티셔츠 등 3종',
 '스텐망등8종구매',
 '육각볼트등17종구매',
 'K1케이블조립체등6종구매',
 'K1 베어링등11종구매',
 '리본부교 튜브조립체등10종구매',
 '다목적전술차 케이블등2종구매',
 '5톤 나사등18종구매',
 '5톤유압크레인 호스조립체등2종구매',
 '5톤유압크레인 호스조립체등2종구매',
 'M48전차 플랜지구매',
 '16년 발칸 증폭기조립체 정비',
 '16년 발칸 증폭기조립체 정비',
 '16년 발칸 증폭기조립체 정비',
 'K55A1자주포 호스조립체등8종구매',
 '5톤 브래킷 구매',
 'K288장갑차 로프등11종구매',
 '화강석(성곽석) 385㎡ 제조',
 '일반의약품 366종 구매',
 '영내관사 보일러 및 분배기 구매/설치',
 '수직천공기 2EA',
 '바나나맛 우유',
 'UPS(무정전전원장치)제조 설치',
 '계룡대 비상용발전기 제조설치 납품',
 '연료유 승압유지밸브',
 'K1개스킷등33종구매',
 'K1개스킷등33종구매',
 'K1와셔등84종구매',
 '2016년 합동임관식 기념품(호부) 제조',
 '임시명찰 등 2품목 제조 구매',
 '엔진브로와 구매',
 '16년 의료용 산소 구매',
 '즉석순대(용기)',
 '즉석순대(용기)',
 '웰부트린 엑스엘 정 등 122품목',
 '쇄석골재 등 3종 구매',
 '체력단련장 유류 (휘발유  경유) 구매',
 '제빙기 구매 설치',
 '가지 등 279종 구매(흑산도 000운용대)',
 '가지 등 279종 구매(흑산도 000전진기지대)',
 '가지 등 306종 구매(욕지도 000전진기지대)',
 '가지 등 306종 구매(욕지도 000감시대)',
 '피자빵',
 '스낵류',
 '샌드형 쿠키',
 '미니약과',
 '00부대 음식물류폐기물 처리용역',
 '16-D-021-철재 장의자 등 5종 제조 납품',
 '16-D-022 회전의자 등 6종 제조 납품',
 '컵스프',
 '초코맛 쿠키',
 '초코바',
 '파이형 쿠키',
 '00부대(6진) 민사반 물품 구매(2차)',
 '덴탈 마스크 50개 등 43품목(물품)',
 '오니푸랄 주사 등 11품목(물품)',
 '오니푸랄 주사 등 11품목(물품)',
 '교과서 163종 구매',
 '00부대(6진) 민사반 물품 구매(3차)',
 '00부대(6진) 민사반 물품 구매(4차)',
 '쇠고기장조림 등 4종(연평도)',
 '무배추김치(김장) 등 8종(연평도)',
 '단무지 등 53종(연평도)',
 '쌀 햄버거빵 등 40종(연평도)',
 '이온음료 등 17종(연평도)',
 '콩나물 등 3종(연평도)',
 '방사선필름 등 5종 구매',
 '종이걸레 등 2종 구매',
 '소시지 구매',
 '소시지 구매',
 '기능성팬티 등 9종 구매',
 '차아염소산나트륨 등 5항목 구매(물자)',
 '16년 장교후보생 증식 구매',
 '16년 장교후보생 증식 구매',
 '오일휀스 8항목 제조(물자)',
 '잔류염소측정시약 등 5항목 구매(물자)',
 '멀티 누설탐지기 구매',
 '16년 대전병원 장비운영소모품(의료용가스) 구매',
 '토너구매( 연간 단가계약)',
 '휴대폰 카드형 보조배터리 2 000개',
 '16-덕-1차 전산운영용품 구매',
 '포장박스 등 3종 제조구매',
 '전기보온물통 등 12종 구매',
 '점화플러그 등 10항목 구매(물품)',
 '점화플러그 등 10항목 구매(물품)',
 '국방 빅데이터 플랫폼 기반 구축사업 리스',
 '16-F-007 이동형 탱크제조 납품',
 '16-F-007 이동형 탱크제조 납품',
 '디젤발전기 400KW 제조설치',
 '리프레쉬플러스 점안액 등 270종',
 '16-F-011 트랙터 레커용 트럭 제조',
 '샌드형 아이스크림 구매',
 '식혜 구매',
 '예비군 도시락',
 '컵형 아이스크림 구매',
 '콘형 아이스크림 구매',
 '팩형 아이스크림 구매',
 '떠먹는발효유 구매',
 '견과류(혼합형) 구매',
 '크림빵 구매',
 '단팥빵 구매(제조)',
 '피자빵 구매(제조)',
 '소보루빵 구매(제조)',
 '감자스낵 구매',
 '초코과자 구매',
 '샌드과자 구매',
 '초코바 구매',
 '초코렛 구매',
 '양갱 구매',
 '감자스낵 구매',
 '초코과자 구매',
 '생수 구매',
 '초코렛 구매',
 '초코렛 구매',
 '초코바 구매',
 '핫바 구매(제조)',
 '16년 설날 경축특식 구매(제조)',
 '16년 설날 경축특식 구매(제조)',
 '체력단련장 식자재 000종 구매',
 '교과서 136종 구매',
 '난방용 LPG 납품(백령도)',
 '액화석유가스(LPG)구매',
 '멸균 거즈 등 35품목 구매(의무)',
 '멸균 거즈 등 35품목 구매(의무)',
 '컨테이너 제작',
 '파이류',
 '콜라',
 '초콜렛',
 '초코바',
 '이온음료',
 '스낵류',
 '미니약과',
 '생수',
 '소보루빵',
 '후식류 식혜 구매',
 '후식류 이온음료 구매',
 '후식류 쌀음료 구매',
 '16-F-010열화상 비파괴검사 장비 구매',
 '후식류 콘형 아이스크림 구매',
 '후식류 샌드형 아이스크림 구매',
 '후식류 팥빙수 아이스크림 구매',
 '증식용 떡 및 생일자 케익크 제조납품',
 '후식류 팩형 아이스크림 구매',
 '후식류 튜브형 아이스크림 구매',
 '후식류 떠먹는 발효유 구매',
 '후식류 견과류 세트 구매',
 '후식류 과일푸딩 구매',
 '떡류 등 18종 제조/납품',
 '16-K-액화석유가스(LPG)',
 '경축특식 만쥬 세트 구매',
 '경축특식 빵세트 구매',
 '후식류 마시는 발효유 구매',
 '슈크림빵 등 9종 구매',
 'K1전차 스프링등11종구매',
 '16-F-012 열화상카메라 구매',
 '체력단련장 락카 소모품 구매',
 '에이스가든 식자재(생가지외 365품목)',
 'K1리드선등14종구매',
 '금속제 정류기 구매',
 'k1오링등17종구매',
 '주파수 변환기 구매',
 'M48전차 나사등32종구매',
 'M48전차 베어링등11종구매',
 'K55A1개스킷등3종구매',
 'K55A1개스킷등3종구매',
 'K55A1베어링등9종구매',
 'K55A1너트등37종구매',
 'K9오링등59종구매',
 'K9스프링등8종구매',
 'K9나사등76종구매',
 'K9밸브등19종구매',
 'K9밸브등19종구매',
 '리본부교 봉합재등42종구매',
 '5톤 볼트등217종구매',
 '5톤브래킷등64종구매',
 '2 1/2톤 니플등62종구매',
 '무선감청장비 축전기등178종구매',
 '설날 경축특식 냉동떡 세트',
 '설날 경축특식 냉동떡 세트',
 '00학교 생도증식 구매',
 '열상장비 스페이서등11종구매',
 '대박격포레이더 반도체장치등4종구매',
 '발칸필터구매',
 '발칸와셔총류등121종구매',
 '(육성) 사단 테블릿PC 구매',
 '두부',
 '순두부',
 '파인애플',
 '견과류(한줌)',
 '콩두유',
 '과일푸딩',
 '과채음료',
 '떠먹는 발효유',
 '마시는 발효유',
 '비타민음료',
 '생수',
 '선봉대체력단련장 유류구매(하이신유)',
 '식혜',
 '아이스크림 샌드형',
 '아이스크림 컵형',
 '아이스크림 콘형',
 '아이스크림 팩형',
 '에이드',
 '이온음료',
 '커피음료',
 '탄산음료',
 '팥빙수',
 '발칸 베어링등15종구매',
 '발칸 기어등14종구매',
 '발칸 베이스조립체등7종구매',
 '도시락',
 '도시락',
 '도시락',
 '발칸 장치대등6종구매',
 '알루미늄 합금판 등 11품목 ',
 '가지 등 163종',
 '돈삼겹(국내산) 등 10종',
 '16년 설 경축특식 떡세트(제조 또는 구매)',
 '16년 환자치료식(함평병원)',
 '16년 환자치료식(부산병원)',
 '16년 환자치료식(고양병원)',
 '16년 환자치료식(양주병원)',
 '16년 환자치료식(일동병원)',
 '16년 환자치료식(청평병원)',
 '16년 환자치료식(홍천병원)',
 '16년 환자치료식(홍천병원)',
 '16-00대학 연간 도서구매',
 '면마스크 등 2품목 구매',
 '충성대 신문제작제157호~제162호)',
 '16년 생도증식(건포도 등 145종) 구매',
 '모듬두텁떡 등 6종 제조',
 '모듬두텁떡 등 6종 제조',
 '삼계탕 등 36종 구매',
 '초코우유 등 38종 구매',
 '근속30주년 보관용 휘장 등 4품목 제조',
 '의무장비(종합효소 연쇄반응 장치) 구매',
 '크린 자연락스 등 35품목',
 '크린 자연락스 등 35품목',
 '생수 구매',
 '바나나맛 우유 구매',
 '콜라 구매',
 '사이다 구매',
 '과일음료 구매',
 '과일탄산음료 구매',
 '식혜 구매',
 '콘형 아이스크림 구매',
 '팩형 아이스크림 구매',
 '컵형 아이스크림 구매',
 '샌드형 아이스크림 구매',
 '팥빙수 구매',
 '마시는발효유 구매',
 '전기이발기 등 2종 구매',
 '16년 의무장비(비인후경) 구매',
 '16년 의무장비(고주파수술기) 구매',
 '16년 의무장비(심장세동제거기) 구매',
 '16년 의무장비(혈액응고측정기) 구매',
 '방수포장백류',
 '방수포장백류',
 '방수포장백류',
 '계룡대 해미르 어린이집 교구교재 구매',
 '세제 세탁용 등 2항목 구매(물자)',
 '제도지 등 2항목 구매(물자)',
 '제도지 등 2항목 구매(물자)',
 '군 숙소 보일러 설치납품(단가)',
 '시추공 매몰방지용 자재(PVC) 제조구매',
 '16년 포구초속측정레이다',
 '중파송신기 유지보수 정비',
 '센서  촉각반응용 등 4품목',
 '의무장비(폐기능측정기) 구매 계약',
 '의무장비(전기수술기병원용) 구매 계약',
 '의무장비(전기수술기내시경용) 구매 계약',
 '의무장비(소생기야전용 등 4건) 구매 계약',
 '플렌지 너트 1 000EA',
 '표시기 산소유출용 1종',
 '모듬콩조림',
 '깻잎무침',
 '무말랭이무침',
 '땅콩조림',
 '고춧잎장아찌',
 '마늘장아찌',
 '명이절임',
 '양념시래기',
 '김자반',
 '미역튀김',
 '명란젓갈',
 '창란젓갈',
 '꼴뚜기젓갈',
 '낙지젓갈',
 '배추김치(포기)',
 '배추김치(포기절단)',
 '깍두기',
 '총각김치',
 '열무김치',
 '파김치',
 '갓김치',
 '백김치',
 '물김치',
 '고급배추김치(포기)',
 '16년 공군 연습용 워게임모델 성능개선 용역',
 '점화플러그 등 22종',
 '입시홍보물품(포스트잇 등 2종) 구매',
 '함정용 위성방송수신안테나 유지보수 정비',
 '16년 증식용 떡 구매',
 '와이프용 구동유니트',
 '와이프용 구동유니트',
 '약기 등 5종',
 '00공사 관급자재 가스절연부하개폐기 구매',
 '자동기상관측장비 등 6종 유지보수 정비',
 '방공관제레이더무선주파수용증폭기외주정비(117E1)',
 '방공관제레이더무선주파수용증폭기외주정비(117E1)',
 '고임쇠 철제 소형 등 5항목 구매(물자)',
 '세척제 일반목적용(20Kg) 1항목 구매(물자)',
 '종이타올',
 '16년 인터넷 유해사이트 차단체계 교체사업',
 '체력단련장 코스관리자재 비료 구매',
 '체력단련장 코스관리자재 농약 구매',
 '체력단련장 코스관리자재 모래 구매',
 '15년 정보보호체계 교체사업 리스',
 '마포대 등 504종',
 '플라스틱 제본링 등 854종',
 '증·후식류 생수 구매',
 '육군 부대기(11종) 제조',
 '병리장비 운영소모품 89종 구매',
 '병리장비 운영소모품 23종 구매',
 '병리장비 운영소모품 63종 구매',
 '병리장비 운영소모품 20종 구매',
 '병리장비 운영소모품 39종 구매',
 '반합',
 '반합',
 '관사 리모델링 창호 구매 및 설치',
 '사각어묵(냉동)',
 '봉어묵(냉동)',
 '연료시스템  모듈식 등 55종',
 '어린이집 아동도서 729종 구매',
 '의장대대 행사용품 구매(해군 의장마크 등 00종)',
 '오렌지',
 '바나나',
 '키위',
 '메론',
 '파인애플',
 '돼지고기등뼈',
 'LA갈비',
 '씻어나온쌀',
 '모듬해물',
 '해물모듬완자',
 '숯불닭강정',
 '감자튀김',
 '생선까스',
 '너비아니',
 '김치만두',
 '동그랑땡',
 '냉동닭꼬치',
 '함박스테이크',
 '치킨너겟',
 '냉동새우',
 '치즈스틱',
 '김말이튀김',
 '새우튀김',
 '탕수육',
 '냉동날치알',
 '군만두',
 '고기만두',
 '알감자 만두',
 '바베큐폭립',
 '청국장',
 '비엔나소시지',
 '게맛살',
 '오리훈제슬라이스',
 '포장족발',
 '후르츠칵테일',
 '꽁치통조림',
 '프레스햄통조림',
 '파인애플통조림',
 '스위트콘',
 '골뱅이통조림',
 '플라이형 제침기 등 183종',
 '구두솔 등 843종',
 '해류유속계 등 8종',
 '16-잠수함 전투복 제조납품',
 '세탁기 트레일러탑제식',
 '세수비누 등 19품목 구매',
 '항-16-002  003 냉장고 극저온식 병원용 등 4종',
 '조리병교육대 교육 재료',
 '조리병교육대 교육 재료',
 '계산기셋트(KM28) 등 4항목 구매(물자)',
 '황산칼륨 등 12항목 구매(물자)',
 '배추김치 등 5품목',
 '깍두기김치 등 3품목',
 '깍두기김치 등 3품목',
 '반판두부 등 14품목',
 '감자수제비 등 23품목',
 '새우패티',
 '그린키위 등 28품목',
 '깻잎무침 등 12품목',
 '마가렛트 등 43품목',
 '지퍼백등18종구매',
 '의료재료 268종 구매',
 '의약품 293종 구매',
 '근속 30주년 기념휘장 등 3종 제조 구매',
 '개스킷 실린더 헤드용 등 13종',
 '플라스틱 소변컵 등 169종',
 '수도병원 일반재료 248종 구매',
 '16년 소형 대공표적기(표적기 등 4품목)',
 '수도병원 외과장비소모품(3) 66종 구매',
 '수도병원 외과장비소모품(1) 37종 구매',
 '수도병원 외과장비소모품(4) 10종 구매',
 '수도병원 외과장비소모품(2) 24종 구매',
 '수도병원 병리재료 126종 구매',
 '수도병원 수술포류 30종 구매',
 '수도병원 치과재료 268종 구매',
 '16-1차 시추공 매몰방지용 자재(흑관 등 9종) 구매',
 '병원장비 소모품 109종 구매',
 '진동분석장비 구매',
 '기타유지물자(비닐)',
 '00부대 F-15K 저장고 신축공사 수배전반 제조 설치',
 '행정소모품(복사용지) 구매',
 '구동제어장치류',
 '특수수술재료(인대고정용 등 7종) 구매',
 '바나나 구매',
 '특수수술재료(금속성ANCHOR 등 2종) 구매',
 '덮개 및 멜빵',
 '생도 태블릿 PC 구매',
 '냉면육수',
 '스테이크소스',
 '햄버그스테이크',
 '데리야끼치킨',
 '삼계탕한방재료',
 '버터',
 '갈색설탕',
 '보리차',
 '카놀라유',
 '생수',
 '건포도',
 '부침가루',
 '즉석밥',
 '추어탕',
 '까나리액젓',
 '짬뽕양념장',
 '수제소시지',
 '동태커틀렛',
 '미향',
 '메밀소스',
 '건토란대',
 '양념 오징어꼬치',
 '생선순살 탕수어',
 '시저드레싱',
 '크래미(냉동)',
 '오리엔탈드레싱',
 '식초',
 '소양념갈비찜',
 '떡볶이떡',
 '떡국떡',
 '뼈다귀해장국',
 '체력단련장 비료 구매',
 '바인더 등 263종',
 '자동차 동력 전달 제어 장치',
 '이온음료',
 '냉동수육삼겹살',
 '멸균딸기우유',
 '멸균초코우유',
 '냉장염지조각닭 등 7종 구매',
 '순살조각닭 등 6종 구매',
 '16년 상승레스텔 및 간부식당 식자재 납품',
 '덴티안 미러핸들 등 152종',
 '포토용지 등 279종',
 '무초산형 실리콘 등 461종',
 'K9베어링구매',
 '16-025 가공탕수육등 165종',
 '건사료 군견용',
 '건사료 군견용',
 '건사료 군견용',
 '비호용 전원공급기(POWER SUPPLY)',
 '군장품(포제약장 등 7종) 제조',
 '에어파스 등 64품목 구매',
 'LED 채널 간판 구매',
 '보온대(주머니난로) 구매',
 '2016년 영선자재 구매',
 '어린이집 비품 32종 구매',
 '삼상유도전동기 등 113종',
 '풀페이스 마스크 등 8종',
 '레스큐 스트롭 등 9종',
 '복사용지 등 207종',
 '어린이집 가전제품 22종 구매',
 '특수강등3종구매',
 '16년 예비군훈련 중식 제조 납품 계약',
 '어린이집 교구교재 310종 구매',
 '어린이집 취사 비품류 100종 구매',
 '인청동판등3종구매',
 '스프링등6종구매',
 '스티카비닐등3종구매',
 '폴리우레탄신나구매',
 '액체알곤 등 5종 구매',
 '경기용탄약구매(트랩탄 스키탄)',
 '아세톤 등 3종',
 '유류흡착패드 등 5종',
 '유류흡착패드 등 5종',
 '파이프 커플링 등 336종',
 '액화석유가스(LPG)',
 '의약품(알레그라디정) 등 123종',
 '토너(P3005/Q7551) 등 53종 구매',
 '무김치 등 8종 제조 납품',
 '16-해군특전 전투복(상  하)제조 납품',
 '16-고속정 항해복 제조 납품',
 '인쇄소모용품 11종 구매',
 '병리장비 운영소모품 38종 구매',
 '병리장비 운영소모품 37종 구매',
 '00부대 지뢰제거작전 개인보호물자 구매',
 '16년 액화석유가스(LPG) 구매',
 '전투식량(전투식량1형(1식단))',
 '전투식량(전투식량1형(2식단))',
 '전투식량(전투식량1형(3식단))',
 '사과 주스',
 '사과 주스',
 '사과 주스',
 '포도주스',
 '포도주스',
 '포도주스',
 '토마토케첩',
 '계체단 구룡코스 전동카 구동배터리 구매설치',
 '13-본-국대-01 00학교 이전 온수저장탱크 제조설치',
 '13-본-국대-01 00학교 이전 온수저장탱크 제조설치',
 '패킹 등 43항목 구매(기장)',
 '볼트 유체 통로용 등 624항목 제조(기장)',
 '실린더 조립체 작동식 선형 등 9항목 제조(기장)',
 '20mm 발칸 링크 구매',
 '16-고속단정 00호정 엔진 정비',
 '마일드참치통조림 등 6종 구매',
 '00지역 CCTV 설치납품',
 '16-물류작업복(하계T) 등 3종 제조',
 '16-114 디지털카메라 등 14종',
 '연막탄발사기부품류',
 '터빈 연료 항공용(JP-8)(화차A지역)',
 '터빈연료 항공용(제트유)',
 '터빈연료 항공용(제트유)',
 '준공검사 검측장비 구매',
 '고압공기압축기 및 베어링 슬리브형',
 '고압공기압축기 및 베어링 슬리브형',
 '단무지',
 '간성아파트 건립 발전기 제조납품',
 '간성아파트 건립 자동식소화기 제조납품',
 '간성아파트 건립 펌프 제조설치납품',
 '간성아파트 건립 화재수신기 제조납품',
 '간성아파트 건립 화재수신기 제조납품',
 '간성아파트 건립 전관방송 제조납품',
 '판초우의',
 '16-가방(침투보호의 용)제조',
 '다단식선반(중) 등 3종',
 '가스켓 등 15종',
 '인화점 시험기 구매',
 '유격자격휘장(포제) 등 4종',
 '전산운영용품 구매',
 '업소용 세탁기 제조설치납품',
 '업소용 세탁기 제조설치납품',
 '나일론로프 등 3종',
 '나일론로프 등 3종',
 '의약품(엘디로 정외 33종) 구매',
 '식관',
 '작전영상전송장비(KAISHOT) 유지보수 정비',
 '플러그 등 25종',
 '특수작전식량',
 '혼합간장',
 '고추장',
 '고추장',
 '고추장',
 '인쇄용지 21종 구매',
 '된장',
 '된장',
 '된장',
 '야외화장실(이동식  2동) 구매',
 '유동점시험기 구매',
 '함정용 축',
 '화포부품류',
 '구형화포부품류',
 '송수화기(H-930K)',
 '송수화기(H-930K)',
 '가죽요대 등 2종',
 '하이힐(백색)',
 '방음화',
 '남군백단화',
 '여군백단화',
 '하이힐(백색)',
 '방음화',
 '남군백단화',
 '여군백단화',
 '안테나조립체(AS-992K) 및 부품',
 '항공기 유도차 제조',
 '상온형 노면표지용 도료 등 3종',
 '특전복',
 '00 0000 분석체계 구축',
 '제어장치조립체 및 축 조립체류',
 '제어장치조립체 및 축 조립체류',
 '인쇄판(C.T.P) 및 현상약품 연간 구매',
 '밸브류',
 '16년 발칸 사격통제부부품(구매)',
 '항공유 펌프 3세트 구매',
 'OO함 함안정기 제어반 정비',
 '00함 지원장비(2종) 정비',
 '00함 지원장비(2종) 정비',
 '00단 병사식당 화물용승강기 제조설치',
 '16년 오리콘 사격통제장치 부품류 (제조)',
 '체력단련장(골프장) 잔디 구매설치',
 '궤도부품류(구매)',
 '16년 해병대 지휘소 비디오월 교체사업(리스물건)',
 '공수훈련지상장비',
 '브레이크 슈 세트 등 2항목 제조(기장)',
 '베어링 클러치 릴리이스용 등 16항목 구매(기장)',
 '연결기 조립체 전기용 등 46항목 제조(기장)',
 '호스 비금속제 등 60항목 구매(기장)',
 '호스 조립체 비금속제 등 53항목 제조(기장)',
 '알루미늄 접이식 원형탁자 등 3종',
 '보온식관',
 '보온식관',
 '301캇타 등 183종',
 '폭발물처리차 제조',
 '라벨테이프 등 149품목 구매',
 '희석제  랙커 페인트 등 17종',
 '고정카메라 등 10품목 구매',
 '그린가드후드작업복 등 27종',
 '전산운영용품 구매',
 '단안 야간 투시경 구매',
 '교판(공병 보도조립체 교량용)',
 '교판(공병 보도조립체 교량용)',
 'K21장갑차 발전기 엔진보조용 외주정비',
 'K21장갑차 발전기 엔진보조용 외주정비',
 '프로그래머 등 4종 제조',
 '프로그래머 등 4종 제조',
 '피스톤 컴플레트 외 13종(압축기 부품)',
 '방화복',
 '16년 발칸용 아크릴',
 '16년 발칸용 아크릴',
 '16년 발칸용 아크릴',
 '16년 발칸용 아크릴',
 '16년 발칸용 아크릴',
 '16년 발칸 게이지류',
 '16년 발칸 게이지류',
 '수색휘장 등 18품목 구매',
 'Truepress Jet520 전용잉크(CMYK) 등 6종 구매',
 '16-F-003  압축기 유니트 제조 납품',
 '16-F-003  압축기 유니트 제조 납품',
 '확성기세트 부품',
 '변압기  펄스용(GPS-98K용)',
 '변환기조립체(PHS-32용)',
 '공병우의',
 '병사피복(훈련용 모장갑) 제조',
 '비행가죽잠바(공군)',
 '불고기패티 2형(1지역)',
 '불고기패티 2형(2지역)',
 '불고기패티 2형(3지역)',
 '불고기패티 2형(4지역)',
 '새우패티(1지역)',
 '새우패티(2지역)',
 '새우패티(3지역)',
 '새우패티(4지역)',
 '미트볼(1지역)',
 '미트볼(2지역)',
 '미트볼(3지역)',
 '미트볼(4지역)',
 '16-고래2호(해상사격)표적 등 4종 구매',
 '우측 덮개 조립체 등 19항목 구매(총포)',
 '16년 부식분배용 위생 및 포장재료 구매',
 '전동 카운터 스태커 구매/설치',
 '16년 40밀리 연습유탄',
 '의무장비(핵산추출장비) 구매',
 '2016년 의무장비 안과유니트 구매',
 '계체단 계룡코스 전동카 구동배터리 구매 설치',
 'K9볼트등91종구매',
 'K9볼트등91종구매',
 '멀티탭 등 575종',
 '황산',
 '황산',
 '백열등 등 10종',
 '13-본-국대-01 00학교 이전사업 송풍기 제조설치',
 'K9부품키트등9종구매',
 'K9부품키트등9종구매',
 '에이-케이블',
 '함정 상가대 대차휠 정비',
 '2.5톤 이동배식차 제조',
 '딩기요트 5척 구매',
 '밸브류(궤도장비용)',
 '좌석 차량용 등 4항목 제조(궤도)',
 '히터(도관류)',
 '2016년 소도구 취사기구 구매',
 '바  금속제 등 22품목',
 '레이저 프린터 토너(재생) 등 7종 구매',
 '화장지 등 2품목 구매',
 '16년 천마 기화기 조립체 정비',
 '하우징 조립체(500MD 7.62MM)',
 '하우징 조립체(500MD 7.62MM)',
 '구축함 음탐기(DSQS-21BZ) 소나 돔 교체 정비',
 '마요네즈',
 '식초',
 '식초',
 '치즈 슬라이스형',
 '천일염',
 '2016년 의무장비 레이져수술기 이산화탄소 구매',
 '2016년 의무장비 레이져수술기 이산화탄소 구매',
 '2016년 의무장비 전자동 정제 분류 포장기 구매',
 '항-16-010 이소티논연질캡슐 등 38품목',
 '화공가스(9종) 구매설치',
 '00지역 연미복 제조납품',
 '소형표적기 완제품 및 조종기 제조',
 '암  와이퍼용 등 46항목 제조(기장)',
 '릴리스 실린더 조립체 등 22항목 구매(기장)',
 '산악장비셋및부품',
 ...]

In [ ]:
a_title_df = pd.DataFrame(a_list)

file_name = 'a_title_df1.csv'
a_title_df.to_csv(file_name, index=False, encoding='cp949')

In [22]:
okt = Okt()
words_list = []
stop_words = ['구매']
for i in range(len(a_list)):
    text = a_list[i]
    morp = okt.pos(text, stem=True) # stem = 동사 원형 추출

    # 명사와 동사/형용사 추출, 한 글자 단어 삭제, 불용어 제거
    for word, tag in morp:
        if ((tag == 'Noun')
            and (len(word) > 1)
            and (word not in stop_words)):
            words_list.append(word)

words_list

KeyboardInterrupt:

In [20]:
word_freq = nltk.FreqDist(words_list)
word = word_freq.keys()
freq = list(word_freq.values())
word_count_df = pd.DataFrame([word , freq],
                    index = ["word","freq"]).T
word_count_df.sort_values(["freq"],
                           ascending= False ,
                           inplace=True)
word_count_df

      word   freq
10      구매  29703
33      제조   9026
94      항목   6193
13      장비   4642
44      품목   3535
...    ...    ...
6109    화교      1
4333  여압누출      1
6111    구취      1
6112    로탈      1
7998   민수형      1

[7999 rows x 2 columns]

In [ ]:
file_name = 'WC.csv'
word_count_df.to_csv(file_name, index=False, encoding='utf-8')

In [25]:
file_name = 'a.csv'
a_df.to_csv(file_name, index=False, encoding='utf-8')