### 입찰결과 (물품) 의 공고명 분류와 분류별 겹치는 행 찾기

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from konlpy.tag import Okt, Kkma, Komoran
from collections import Counter
import pickle

In [3]:
path = 'workbookdata/입찰결과물품_df.csv'
입찰결과물품df = pd.read_csv(path, encoding='cp949')
결과_입찰공고명 = 입찰결과물품df.입찰공고명

In [5]:
def categorizeBig(df, category):
    # 카테고리별 pick_list와 remove_list 정의
    category_keywords = {
        '1종':{
            'pick_list': ['빙수', '바나나', '우유', '콜라', '과일', '탄산', '음료', '탄산수', '알로', '발효', '젤리', '견과', '치즈케이크', '브레드', '짜장', '컵밥',
            '허니', '감자', '스낵', '식용', '탄산음료', '핫바', '소시지', '어묵', '핫도그', '두부', '떡볶이','쌈무', '메추리', '순대',
            '단무지', '우동', '단호박', '샐러드', '고구마', '메밀', '국수', '모짜렐라', '치즈', '라이스', '스파게티', '사과', '푸딩', '망고', '요거트', '국수',
            '콘푸', '마카로니', '돈까스', '소스', '칠리소스', '데리야끼', '반장', '캡사이신', '굴소스', '간장', '초콜릿', '마가렛', '베리',
            '초코파이', '초코', '에너지', '몽쉘', '사이다', '매실', '포도', '식혜', '옥수수', '두유', '요거트', '요구르트', '복숭아', '아이스티', '코코넛', 
            '농축액', '피자' '케익', '머핀', '견과류', '부식', '분식', '채류', '김치', '호떡','쿠키', '미니', '약과', '음식', '쇠고기', 
            '조림','김치', '햄버거', '나물', '아이스크림', '도시락', '단팥', '소보루빵', '과자', '샌드','초코렛', '양갱','생수','초콜렛', '후식',
            '떡류', '만쥬', '슈크림', '순두부', '애플', '과채', '비타민','커피','삼겹',  '건포도','삼계탕', '초코', '우유', '조림', '깻잎', '말랭이', '땅콩',
            '춧잎', '장아찌', '장아찌', '절임', '양념', '시래기', '김자', '미역', '튀김', '명란', '젓갈', '창란', '꼴뚜기', '낙지', '깍두기', 
            '김치', '키위', '메론', '돼지', '고기', '등뼈', '갈비', '해물', '숯불', '강정', '생선',
            '까스', '너비아니', '만두', '동그랑땡', '닭꼬치', '함박', '스테이크', '치킨', '너겟', '새우', '치즈스틱', '김말이', '탕수육', '날치', '고기만', '바베큐', 
            '폭립', '청국장', '소시지', '게맛살', '오리', '훈제', '족발', '후르', '칵테일', '꽁치', '통조림',  '스위트콘', '골뱅이'
            '냉면', '육수', '스테이크', '햄버그', '버터', '갈색', '설탕', '보리차', '가루', '즉석밥', '추어탕', '까나리', '액젓', '짬뽕', 
            '양념', '수제', '동태', '커틀렛', '메밀', '토란', '오징어', '꼬치', '드레싱', '식초', '갈비찜', '떡국', '해장국', '삼겹살', '딸기',
            '전투식량', '식단', '주스', '포도주스', '토마토', '케첩','시리얼' ,'비빔', '쌀맛', '쌀국수', '곰탕', '감자', '버섯', '오이', '피클',
             '수산물', '가자미', '계란', '농산물', '농산', '수산', '축산', '고추', '야채', '소갈비', '살햄','후추',  '한식', '쌈장', '들깨', '조미료',
            '기름', '샌드위치', '볶음', '팝콘', '생선묵', '육개장', '빵가루', '쫄면', '자장면', '가락국수','버섯',  '케찹', '미트', '유제품', '황도'
            '파스타', '주류', '채소',  '맛술', '연어', '양송이', '재첩국', '버팔로', '치킨', '해쉬', '포테이토', '스팸', '맥주', '물냉면', '갈비탕',
            '후춧가루', '라멘', '통닭', '구이', '돼지', '도너츠', '쌍화', '소보로빵', '냉동식품', '영양식', '쵸코', '푸실리', '식빵', '생강', '홍합', '꽃게', '바지락',
            '닭다리', '정육', '버섯', '생면', '원유', '비빔밥', '나물', '카라멜', '생삽겹살', '호박죽', '레토르트', '발사믹', '춘장', '팥죽', 
            '매콤', '계란','차돌박이', '다시다',  '고로케', '곤약', '베이컨', '체다', '생일케이크', '어패류', '깐풍기','가쓰오부시','케익','교자', 
            '까르보나라', '부대찌개', '막대과자', '찹쌀', '육전', '만두', '할라피뇨', '모듬햄', '소시지', '소세지','아몬드', '차돌', '된장','찌개', '과즙', '사과주스',
            '도토리묵', '스팸형햄','훈제오리', '고등어', '곡류', '순두부찌개','돈육' '찐빵', '오이지', '크로크무슈', '간편식','애플', '코코아', '유산균', 
            '카페라떼', '카페인', '딸기스무디', '라떼','가래떡', '타코야끼', '소스류','생크림', '보쌈김치', '연근조림', '우엉', '배맛',  '샘표', '닭윙', '닭봉',
            '대패', '스팸형', '버팔로윙', '호빵', '아이스크림류', '부챗살', '옹심이','찹쌀떡', '갈릭', '크로와상', '먹는샘물', '에너지음료', '새우깡', 
            '캔커피', '치즈', '비요뜨', '마들렌', '전투식량', '환자식', '급식', '빵류', '육류', '면류','빵'],
            'remove_list':['기구', '냉동고', '에너지', '장치','제조기', '장비', '압축기', '오리콘','폐기물', '멜빵']
        },

        '4종': {
            'pick_list': ['목재류','건축용', '아파트', '숙소', '제조설치', '철재', '철근', '철선', \
                  '페인트', '시멘트', '보일러', '콘크리트', '아스팔트', '벽돌', '타일', '생활관', \
                  '토목', '강관', '신축'],
            'remove_list': ['병원', '의무', '치료']
        },
        '8종': {
            'pick_list': ['병원', '환자', '의무', '외상', '안과', '자극', '신경', '의학', \
                 '이비인후과', '치과', '붕대', '외과', '수술', '의료', '병리', '예방약', \
                 '방사선장비', '의약품', '치료', '안경제작', '위생'],
            'remove_list': ['신축', '보일러', '제조설치']
        },
        '테스트':{
            'pick_list': ['밥'],
            'remove_list':['기구', '냉동고', '에너지', '장치','제조기', '장비', '압축기', '오리콘','폐기물','멜빵']
        }
    }
    
    # 유효한 카테고리인지 확인
    if category not in category_keywords:
        raise ValueError(f"지원하지 않는 카테고리: {category}. 지원 카테고리: {list(category_keywords.keys())}")
    
    # pick_list와 remove_list 가져오기
    pick_list = category_keywords[category]['pick_list']
    remove_list = category_keywords[category]['remove_list']
    
    # 정규표현식 패턴 생성
    pick_pattern = '|'.join(pick_list)
    
    # pick_list로 필터링
    result_df = df[df['입찰공고명'].str.contains(pick_pattern, na=False, regex=True)]
    
    # remove_list가 비어 있지 않으면 제거 필터링
    if remove_list and remove_list != ['']:
        remove_pattern = '|'.join(remove_list)
        result_df = result_df[~result_df['입찰공고명'].str.contains(remove_pattern, na=False, regex=True)]
    
    # 필요한 컬럼만 선택
    result_df = result_df[['입찰공고명', '공고기관명']]
    print(f'{category} 결과 건수: {len(result_df)}건')

    return result_df
    
시험 = categorizeBig(입찰결과물품df, '테스트')
시험.입찰공고명.unique()

# 일종 = categorizeBig(입찰결과물품df, '1종')
# 일종.입찰공고명.unique()

테스트 결과 건수: 70건

array(['짜장컵밥 구매', '즉석밥', '밥솥 25EA 구매', '전기 인덕션 국.밥솥 등 2종 구매설치',
       '밥공기 등 0종 구매', '짜장컵밥', '컵밥', '전기밥솥 등 2종',
       '17-6차 일반의무비품(전기밥솥 등 3건) 구매', '가스취사밥솥 구매', '자동밥솥 등 378품목',
       '전기밥솥 등 40품목 구매', '부대조달증식(짜장컵밥) 구매', '압력밥솥 등 2종', '즉석식품류(컵밥)',
       '컵비빔밥/고추장나물비빔밥 등 15종 구매', '전기밥솥(35인용) 288EA 구매',
       '전투식량  S형(쇠고기 고추장 비빔밥)', '전투식량  S형(김치 비빔밥)', '전투식량  S형(카레 비빔밥)',
       '전투식량  S형(해물 비빔밥)', '전투식량  S형(닭고기 비빔밥)', '불닭마요덮밥 등 28종',
       '20-전기밥솥 등 5종 구매', '가스자동밥솥(소형) 1품목 구매', '전기밥솥 등 2품목 구매',
       '전투식량 S형(쇠고기 고추장 비빔밥)', '전투식량 S형(김치 비빔밥)', '전투식량 S형(닭고기 비빔밥)',
       '가스자동밥솥 소형 1항목 구매', '통새우볶음밥', '잡채볶음밥', '전기밥솥 등 5종 구매', '소불고기덮밥소스',
       '밥솥 등 7품목 구매', '불닭마요덮밥 등 13종', '즉석밥 등 5종 구매', '불닭마요덮밥 등 13종 구매',
       '컵밥 구매', '닭고기 덮밥소스 구매', '큐브매콤덮밥소스 등 25종 구매',
       '가스자동밥솥 등 3항목 구매(일반물자)', '참치마요덮밥 등 15종 구매',
       '23-2차 부대계약 증식(컵밥 등 2종) 구매', '전투부식(김치날치알밥 등 14품목) 구매',
       '계약)병사식당 식사재(자율부식비 및 즉석밥) 구매', '23년 간편식(즉석밥 등 26종) 급식품목 구매',
       '컵밥 등 11종', '철판김치덮밥 등 28종 구매', '가스자동밥솥 소형 등 3항목 구매(물자)',
       '가스자동밥솥 소형 등 2항목 구매(물자)', '전투부식(김치날치알밥 등 13품목) 구매'], dtype=object)

In [36]:
일종 = categorizeBig(입찰결과물품df, '1종')
사종 = categorizeBig(입찰결과물품df, '4종')
일종

1종 결과 건수: 6990건
4종 결과 건수: 2285건

                          입찰공고명      공고기관명
7                        팥빙수 구매    제2167부대
8                      바나나우유 구매    제2167부대
9                         콜라 구매    제2167부대
10                      과일탄산 구매    제2167부대
13                      혼합음료 구매    제2167부대
...                         ...        ...
61016    24년 10~12월 부대계약(빵류) 구매  육군제53보병사단
61135  24년 4분기 부대계약부식(빵류) 제조/구매    제6335부대
61137  24-물용-010 민수용 전투식량 구매 계약     6112부대
61141     24년 000부대 삼겹살 등 130품목    제9965부대
61420    민수형 전투식량(함수형) 구매(X116)    제7162부대

[6990 rows x 2 columns]

In [16]:
팔종 = categorizeBig(입찰결과물품df, '8종')
팔종

8종 결과 건수: 3503건

                            입찰공고명    공고기관명
5      16년 대전병원 장비운영유지비(외과장비3) 구매   국군대전병원
6      16년 대전병원 장비운영유지비(외과장비1) 구매   국군대전병원
11      16년 대전병원 장비운영유지비(영상장비) 구매   국군대전병원
12      16년 대전병원 장비운영유지비(영상장비) 구매   국군대전병원
60           대전병원 병리재료 소모품 67종 구매  국군재정관리단
...                           ...      ...
61400       24년 재투자 의무장비(손세척대) 구매   국군수도병원
61406          의무장비(비디오 기도삽관기) 구매  제9691부대
61421     24년 의무장비(전자동정제분류포장기) 구매  국군의무사령부
61422  24년 의무장비(자동분석기 생화학용 중형) 구매  국군의무사령부
61423     24년 의무장비(자동혈구계산기 중형) 구매  국군의무사령부

[3503 rows x 2 columns]

In [24]:
def checkDuplicatesInBidName(classA, classB):
    Adf = categorizeBig(입찰결과물품df, classA)
    Bdf = categorizeBig(입찰결과물품df, classB)
    sameDF = Adf[Adf['입찰공고명'].isin(Bdf['입찰공고명'])]
    return sameDF

In [25]:
checkDuplicatesInBidName('4종', '8종')

4종 결과 건수: 2285건
8종 결과 건수: 3503건

Empty DataFrame
Columns: [입찰공고명, 공고기관명]
Index: []

In [20]:
# 원본에서 각 종류를 제외한 표
def remaining_df(original_df, categorized_df):
    result_df = original_df[~original_df.index.isin(categorized_df.index)]
    result_df = result_df[['입찰공고명', '공고기관명']]
    return result_df

In [37]:
현재구분된종제외df = remaining_df(입찰결과물품df, 일종)
현재구분된종제외df = remaining_df(현재구분된종제외df, 사종)
현재구분된종제외df = remaining_df(현재구분된종제외df, 팔종)
현재구분된종제외df

                                 입찰공고명    공고기관명
0      00부대 물절약 투자대행사업(WASCO  15-A048)  국군재정관리단
1                          155밀리 모의신관류    방위사업청
2                          155밀리 모의신관류    방위사업청
3                          155밀리 모의신관류    방위사업청
4                         스펙트럼용 분석기 구매  국군재정관리단
...                                ...      ...
61427    심해잠수체계(PTC  Wet Bell) 유지보수 정비  해군군수사령부
61428     24-B-대형 에어컨 등 5품목 구매 납품 및 설치  제9196부대
61429         (246361-D) 소형 탑승식 청소차 구매  국군재정관리단
61430             (246343-D) VR HMD 구매  국군재정관리단
61431                24-M-공업용 헬륨가스 구매   국군재정관리단

[48752 rows x 2 columns]

In [42]:
print(len(현재구분된종제외df.입찰공고명.unique()), 현재구분된종제외df.입찰공고명.unique())

36192 ['00부대 물절약 투자대행사업(WASCO  15-A048)' '155밀리 모의신관류' '스펙트럼용 분석기 구매' ...
 '(246361-D) 소형 탑승식 청소차 구매' '(246343-D) VR HMD 구매' '24-M-공업용 헬륨가스 구매 ']

In [38]:
folder_path = 'workbookdata'

## CSV 파일로 저장
output_path = os.path.join(folder_path, 'RemainDF.csv')
현재구분된종제외df.to_csv(output_path, encoding='cp949')

In [ ]:
메모리 비우기
binList = []
입찰공고token = []
df = pd.DataFrame(binList)