In [ ]:
## 수요기관 군대 별 분류

In [70]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd
import json
from urllib.request import urlopen

df = pd.read_csv("C:/theBoram4Jo/hasun/Total 물품 낙찰 결과.csv", encoding="cp949")

if "발주기관" in df.columns:
    print("발주기관")
    print(df["발주기관"])  # 앞 20개만
    print("총 개수:", df["발주기관"].notna().sum())
else:
    print("⚠️ '발주기관' 컬럼이 없습니다. 실제 컬럼들:", df.columns.tolist())

발주기관
0          제3283부대
1            육군훈련소
2          제2307부대
3          국군재정관리단
4          제2307부대
           ...
74727      제9911부대
74728       공군사관학교
74729    해군제3함대사령부
74730      제3707부대
74731      제7001부대
Name: 발주기관, Length: 74732, dtype: object
총 개수: 74732

In [71]:
all_orgs = df["발주기관"]

unique_orgs = all_orgs.drop_duplicates()
print(df["발주기관"].drop_duplicates().to_string(index=False))
print("고유 기관 개수:", unique_orgs.nunique())

unique_list = unique_orgs.tolist()

             제3283부대
               육군훈련소
             제2307부대
             국군재정관리단
              공군사관학교
              제1보병사단
             공군교육사령부
             제9691부대
              제5보병사단
 항공기계약팀 (구:19.09.16)
             제3훈련비행단
             제9965부대
             제9196부대
             제7016부대
             국군의무사령부
            국방부근무지원단
           수도기계화보병사단
                제2군단
             제21보병사단
           제1군수지원사령부
              특수전사령부
             육군군수사령부
              제7보병사단
             제3170부대
           해군제3함대사령부
             해군군수사령부
              국군대전병원
             육군3사관학교
        공군제15특수임무비행단
              국군수도병원
             제9181부대
          공군제19전투비행단
             국방출판지원단
             제7789부대
          육군과학화전투훈련단
             제28보병사단
             합동군사대학교
           공군방공관제사령부
             육군 제1군단
            5군수지원사령부
           국군지휘통신사령부
           국방통합데이터센터
             공군군수사령부
           제9보병사단사령부
          해군 기동함대사령부
          공군제17전투비행단
             육군인사사령부
        방위사업청(운영지원과)
           제1방공유도탄여단
  공군 작사예하 방포사예하 제2여단
            국군간호사관학교
              국군체육부대
             제7821부대
              4284부대
             해군제2수리창
         국방부계룡대근무지원단
             제55보병사단
             제3697부대
          공군제11전투비행단
             제2632부대
             제1862부대
             제9227부대
          육군 제37보병사단
             제5군단사령부
지휘정찰계약팀 (구:19.09.16)
               국군복지단
              제6보병사단
             해군작전사령부
            재경근무지원대대
유도무기계약팀 (구:19.09.16)
             제3707부대
             제22보병사단
                육군본부
                제7군단
             제25보병사단
             제5897부대
             국방부조사본부
             제2167부대
             육군항공사령부
             제2작전사령부
               국방대학교
             육군기계화학교
                수도군단
             제9911부대
            육군종합군수학교
         합동상호운용성기술센터
             제6955부대
             육군 제8군단
             제36보병사단
         공군제5공중기동비행단
             제7001부대
                해군본부
             육군부사관학교
             국군수송사령부
             제8385부대
             제11기동사단
          공군미사일방어사령부
              국군의무학교
              해군사관학교
             제15보병사단
           육군전투지휘훈련단
             제9121부대
           육군제53보병사단
             제7297부대
             제2002부대
           육군 52보병사단
             제5181부대
             제17보병사단
          공군제18전투비행단
             제2067부대
             제6군단사령부
           공군작사근무지원단
             육군종합정비창
             제5738부대
              제8기동사단
             제6276부대
             제1607부대
             제1987부대
             제6755부대
              제3공병여단
              육군항공학교
             해군교육사령부
             제6128부대
           공군제1전투비행단
             제1729부대
             제7851부대
             제1891부대
                연평부대
             제1989부대
         공군제38전투비행전대
            제20전투비행단
              제3보병사단
             해군제1수리창
             육군교육사령부
             국방지형정보단
             제9251부대
              제9해병여단
             제60보병사단
          육군상무대근무지원단
             국방전산정보원
             제32보병사단
          공군 제8전투비행단
            육군종합행정학교
             제1363부대
             제1288부대
              육군보병학교
              합동참모본부
          육군 탄약지원사령부
             제51보병사단
          국군화생방방호사령부
기동화력계약팀 (구:19.09.16)
             수도방위사령부
              육군사관학교
일반장비계약팀 (구:19.09.16)
                공군본부
          공군제10전투비행단
            육군학생군사학교
               물자계약팀
          공군제16전투비행단
            제3공수특전여단
              국방정보본부
             공군항공안전단
            육군정보통신학교
             급식유류계약팀
              육군포병학교
통신장비계약팀 (구:19.09.16)
  함정계약팀 (구:19.09.16)
             국방정신전력원
             제9912부대
             제7856부대
             제5757부대
          공군제7항공통신전대
             제7201부대
              육군공병학교
              국방시설본부
               특수전학교
                1보급단
             제2236부대
              국방부검찰단
  공군 작사예하 방포사예하 제3여단
             제5808부대
          육군 제30기갑여단
              육군방공학교
          국방부유해발굴감식단
             제6293부대
             제5602부대
              육군화학학교
             제7862부대
           자운대근무지원연대
             제75보병사단
             국립서울현충원
             제8278부대
            한미연합군사령부
             동원전력사령부
          국방부(운영지원과)
            제2군수지원여단
             제5925부대
           국군제1068부대
             제5767부대
            제3군수지원여단
              육군정보학교
           공중기동정찰사령부
             지상작전사령부
         지상공통전력운영계약팀
            제 2167부대
             기동총괄계약팀
             함정총괄계약팀
       미래전력사업전력운영계약팀
             화력총괄계약팀
         한국형잠수함총괄계약팀
             제6953부대
           육군제7789부대
                화력여단
         공군83정보통신정비창
             헬기총괄계약팀
             공군작전사령부
           국방부고등군사법원
           유도무기총괄계약팀
         우주지휘통신총괄계약팀
          방사청(테스트기관)
           첨단기술총괄계약팀
              특수함계약팀
             제3739부대
             제3190부대
           육군 제1포병여단
             제20기갑여단
           육군제6501부대
            제2신속대응사단
                육군대학
           감시전자총괄계약팀
            항공기총괄계약팀
             39정찰비행단
                해군대학
               종합보급창
           육군제7163부대
             국제평화지원단
             제2112부대
             제7군수지원단
             국방과학연구소
             드론작전사령부
             제2238부대
             국방기술품질원
       육군 1군 102기갑여단
               전략사령부
         해상공중전력운영계약팀
고유 기관 개수: 245

In [77]:
unique_orgs = df["발주기관"].drop_duplicates()

army = unique_orgs[unique_orgs.str.contains("육군", na=False)]
navy = unique_orgs[unique_orgs.str.contains("해군", na=False)]
air  = unique_orgs[unique_orgs.str.contains("공군", na=False)]
mask = ~(unique_orgs.str.contains("육군|해군|공군", na=False))
others = unique_orgs[mask]

print("육군")
print(army.to_string(index=False))

print("\n\n해군")
print(navy.to_string(index=False))

print("\n\n공군")
print(air.to_string(index=False))

print("\n\n기타")
print(others.to_string(index=False))

육군
        육군훈련소
      육군군수사령부
      육군3사관학교
   육군과학화전투훈련단
      육군 제1군단
      육군인사사령부
   육군 제37보병사단
         육군본부
      육군항공사령부
      육군기계화학교
     육군종합군수학교
      육군 제8군단
      육군부사관학교
    육군전투지휘훈련단
    육군제53보병사단
    육군 52보병사단
      육군종합정비창
       육군항공학교
      육군교육사령부
   육군상무대근무지원단
     육군종합행정학교
       육군보병학교
   육군 탄약지원사령부
       육군사관학교
     육군학생군사학교
     육군정보통신학교
       육군포병학교
       육군공병학교
   육군 제30기갑여단
       육군방공학교
       육군화학학교
       육군정보학교
    육군제7789부대
    육군 제1포병여단
    육군제6501부대
         육군대학
    육군제7163부대
육군 1군 102기갑여단


해군
 해군제3함대사령부
   해군군수사령부
해군 기동함대사령부
   해군제2수리창
   해군작전사령부
      해군본부
    해군사관학교
   해군교육사령부
   해군제1수리창
      해군대학


공군
            공군사관학교
           공군교육사령부
      공군제15특수임무비행단
        공군제19전투비행단
         공군방공관제사령부
           공군군수사령부
        공군제17전투비행단
공군 작사예하 방포사예하 제2여단
        공군제11전투비행단
       공군제5공중기동비행단
        공군미사일방어사령부
        공군제18전투비행단
         공군작사근무지원단
         공군제1전투비행단
       공군제38전투비행전대
        공군 제8전투비행단
              공군본부
        공군제10전투비행단
        공군제16전투비행단
           공군항공안전단
        공군제7항공통신전대
공군 작사예하 방포사예하 제3여단
       공군83정보통신정비창
           공군작전사령부


기타
             제3283부대
             제2307부대
             국군재정관리단
              제1보병사단
             제9691부대
              제5보병사단
 항공기계약팀 (구:19.09.16)
             제3훈련비행단
             제9965부대
             제9196부대
             제7016부대
             국군의무사령부
            국방부근무지원단
           수도기계화보병사단
                제2군단
             제21보병사단
           제1군수지원사령부
              특수전사령부
              제7보병사단
             제3170부대
              국군대전병원
              국군수도병원
             제9181부대
             국방출판지원단
             제7789부대
             제28보병사단
             합동군사대학교
            5군수지원사령부
           국군지휘통신사령부
           국방통합데이터센터
           제9보병사단사령부
        방위사업청(운영지원과)
           제1방공유도탄여단
            국군간호사관학교
              국군체육부대
             제7821부대
              4284부대
         국방부계룡대근무지원단
             제55보병사단
             제3697부대
             제2632부대
             제1862부대
             제9227부대
             제5군단사령부
지휘정찰계약팀 (구:19.09.16)
               국군복지단
              제6보병사단
            재경근무지원대대
유도무기계약팀 (구:19.09.16)
             제3707부대
             제22보병사단
                제7군단
             제25보병사단
             제5897부대
             국방부조사본부
             제2167부대
             제2작전사령부
               국방대학교
                수도군단
             제9911부대
         합동상호운용성기술센터
             제6955부대
             제36보병사단
             제7001부대
             국군수송사령부
             제8385부대
             제11기동사단
              국군의무학교
             제15보병사단
             제9121부대
             제7297부대
             제2002부대
             제5181부대
             제17보병사단
             제2067부대
             제6군단사령부
             제5738부대
              제8기동사단
             제6276부대
             제1607부대
             제1987부대
             제6755부대
              제3공병여단
             제6128부대
             제1729부대
             제7851부대
             제1891부대
                연평부대
             제1989부대
            제20전투비행단
              제3보병사단
             국방지형정보단
             제9251부대
              제9해병여단
             제60보병사단
             국방전산정보원
             제32보병사단
             제1363부대
             제1288부대
              합동참모본부
             제51보병사단
          국군화생방방호사령부
기동화력계약팀 (구:19.09.16)
             수도방위사령부
일반장비계약팀 (구:19.09.16)
               물자계약팀
            제3공수특전여단
              국방정보본부
             급식유류계약팀
통신장비계약팀 (구:19.09.16)
  함정계약팀 (구:19.09.16)
             국방정신전력원
             제9912부대
             제7856부대
             제5757부대
             제7201부대
              국방시설본부
               특수전학교
                1보급단
             제2236부대
              국방부검찰단
             제5808부대
          국방부유해발굴감식단
             제6293부대
             제5602부대
             제7862부대
           자운대근무지원연대
             제75보병사단
             국립서울현충원
             제8278부대
            한미연합군사령부
             동원전력사령부
          국방부(운영지원과)
            제2군수지원여단
             제5925부대
           국군제1068부대
             제5767부대
            제3군수지원여단
           공중기동정찰사령부
             지상작전사령부
         지상공통전력운영계약팀
            제 2167부대
             기동총괄계약팀
             함정총괄계약팀
       미래전력사업전력운영계약팀
             화력총괄계약팀
         한국형잠수함총괄계약팀
             제6953부대
                화력여단
             헬기총괄계약팀
           국방부고등군사법원
           유도무기총괄계약팀
         우주지휘통신총괄계약팀
          방사청(테스트기관)
           첨단기술총괄계약팀
              특수함계약팀
             제3739부대
             제3190부대
             제20기갑여단
            제2신속대응사단
           감시전자총괄계약팀
            항공기총괄계약팀
             39정찰비행단
               종합보급창
             국제평화지원단
             제2112부대
             제7군수지원단
             국방과학연구소
             드론작전사령부
             제2238부대
             국방기술품질원
               전략사령부
         해상공중전력운영계약팀

In [78]:
df["군 분류"] = "기타"

# 조건별로 갱신
df.loc[df["발주기관"].str.contains("육군", na=False), "군 분류"] = "육군"
df.loc[df["발주기관"].str.contains("해군", na=False), "군 분류"] = "해군"
df.loc[df["발주기관"].str.contains("공군", na=False), "군 분류"] = "공군"

In [80]:
df.to_csv(r"C:/theBoram4Jo/hasun/Total 물품 낙찰 결과.csv", 
          index=False, 
          encoding="utf-8-sig")

In [99]:
# 기존 classification_map 딕셔너리에 이어서 추가
classification_map.update({
"제3283부대": "육군",
"제2307부대": "육군",
"국군재정관리단": "기타",
"제1보병사단": "육군",
"제9691부대": "해병",
"제5보병사단": "육군",
"제3훈련비행단": "공군",
"제9965부대": "육군",
"제9196부대": "해병",
"제7016부대": "국방부직할",
"국군의무사령부": "기타",
"국방부근무지원단": "국방부직할",
"수도기계화보병사단": "육군",
"제2군단": "육군",
"제21보병사단": "육군",
"제1군수지원사령부": "육군",
"특수전사령부": "육군",
"제7보병사단": "육군",
"제3170부대": "육군",
"국군대전병원": "기타",
"국군수도병원": "기타",
"제9181부대": "해병",
"국방출판지원단": "국방부직할",
"제7789부대": "육군",
"제28보병사단": "육군",
"합동군사대학교": "기타",
"5군수지원사령부": "육군",
"국군지휘통신사령부": "국방부직할",
"국방통합데이터센터": "국방부직할",
"제9보병사단사령부": "육군",
"방위사업청(운영지원과)": "국방부직할",
"제1방공유도탄여단": "육군",
"국군간호사관학교": "기타",
"국군체육부대": "기타",
"제7821부대": "육군",
"4284부대": "국방부직할",
"국방부계룡대근무지원단": "국방부직할",
"제55보병사단": "육군",
"제3697부대": "육군",
"제2632부대": "육군",
"제1862부대": "육군",
"제9227부대": "해병",
"제5군단사령부": "육군",
"지휘정찰계약팀 (구:19.09.16)": "국방부직할",
"국군복지단": "기타",
"제6보병사단": "육군",
"재경근무지원대대": "육군",
"유도무기계약팀 (구:19.09.16)": "국방부직할",
"제3707부대": "육군",
"제22보병사단": "육군",
"제7군단": "육군",
"제25보병사단": "육군",
"제5897부대": "육군",
"국방부조사본부": "국방부직할",
"제2167부대": "육군",
"제2작전사령부": "육군",
"국방대학교": "국방부직할",
"수도군단": "육군",
"제9911부대": "해병",
"합동상호운용성기술센터": "국방부직할",
"제6955부대": "육군",
"제36보병사단": "육군",
"제7001부대": "육군",
"국군수송사령부": "육군",
"제8385부대": "해군",
"제11기동사단": "육군",
"국군의무학교": "육군",
"제15보병사단": "육군",
"제9121부대": "해군",
"제7297부대": "육군",
"제2002부대": "해군",
"제5181부대": "육군",
"제17보병사단": "육군",
"제2067부대": "육군",
"제6군단사령부": "육군",
"제5738부대": "해군",
"제8기동사단": "육군",
"제6276부대": "육군",
"제1607부대": "육군",
"제1987부대": "육군",
"제6755부대": "육군",
"제3공병여단": "육군",
"제6128부대": "육군",
"제1729부대": "육군",
"제7851부대": "육군",
"제1891부대": "육군",
"연평부대": "해병",
"제1989부대": "육군",
"제20전투비행단": "공군",
"제3보병사단": "육군",
"국방지형정보단": "국방부직할",
"제9251부대": "육군",
"제9해병여단": "해병",
"제60보병사단": "육군",
"국방전산정보원": "국방부직할",
"제32보병사단": "육군",
"제1363부대": "국방부직할",
"제1288부대": "육군",
"합동참모본부": "국방부직할",
"제51보병사단": "육군",
"국군화생방방호사령부": "육군",
"기동화력계약팀 (구:19.09.16)": "국방부직할",
"수도방위사령부": "육군",
"일반장비계약팀 (구:19.09.16)": "국방부직할",
"물자계약팀": "국방부직할",
"제3공수특전여단": "육군",
"국방정보본부": "국방부직할",
"급식유류계약팀": "국방부직할",
"통신장비계약팀 (구:19.09.16)": "국방부직할",
"함정계약팀 (구:19.09.16)": "국방부직할",
"국방정신전력원": "국방부직할",
"제9912부대": "해병",
"제7856부대": "육군",
"제5757부대": "육군",
"제7201부대": "육군",
"국방시설본부": "국방부직할",
"특수전학교": "육군",
"1보급단": "육군",
"제2236부대": "육군",
"국방부검찰단": "국방부직할",
"제5808부대": "육군",
"국방부유해발굴감식단": "국방부직할",
"제6293부대": "육군",
"제5602부대": "육군",
"제7862부대": "육군",
"자운대근무지원연대": "국방부직할",
"제75보병사단": "육군",
"국립서울현충원": "기타",
"제8278부대": "육군",
"한미연합군사령부": "기타",
"동원전력사령부": "육군",
"국방부(운영지원과)": "국방부직할",
"제2군수지원여단": "육군",
"제5925부대": "육군",
"국군제1068부대": "국방부직할",
"제5767부대": "육군",
"제3군수지원여단": "육군",
"공중기동정찰사령부": "공군",
"지상작전사령부": "육군",
"지상공통전력운영계약팀": "국방부직할",
"제 2167부대": "육군",
"기동총괄계약팀": "국방부직할",
"함정총괄계약팀": "국방부직할",
"미래전력사업전력운영계약팀": "국방부직할",
"화력총괄계약팀": "국방부직할",
"한국형잠수함총괄계약팀": "국방부직할",
"제6953부대": "육군",
"화력여단": "육군",
"헬기총괄계약팀": "국방부직할",
"국방부고등군사법원": "국방부직할",
"유도무기총괄계약팀": "국방부직할",
"우주지휘통신총괄계약팀": "국방부직할",
"방사청(테스트기관)": "국방부직할",
"첨단기술총괄계약팀": "국방부직할",
"특수함계약팀": "국방부직할",
"제3739부대": "육군",
"제3190부대": "육군",
"제20기갑여단": "육군",
"제2신속대응사단": "육군",
"감시전자총괄계약팀": "국방부직할",
"항공기총괄계약팀": "국방부직할",
"39정찰비행단": "공군",
"종합보급창": "육군",
"국제평화지원단": "국방부직할",
"제2112부대": "육군",
"제7군수지원단": "육군",
"국방과학연구소": "국방부직할",
"드론작전사령부": "육군",
"제2238부대": "육군",
"국방기술품질원": "국방부직할",
"전략사령부": "국방부직할",
"해상공중전력운영계약팀": "국방부직할",
"항공기계약팀 (구:19.09.16)": "국방부직할", 
"해군 기동함대사령부": "해군", 
"육군 제37보병사단": "육군",
"육군항공사령부": "육군",
"해군제1수리창": "해군",
"공군 작사예하 방포사예하 제3여단": "공군",
"육군 1군 102기갑여단": "육군",
"육군 제1포병여단": "육군", 
"육군 제30기갑여단": "육군",
"육군 제37보병사단": "육군",
"육군 탄약지원사령부": "육군",
"육군 방공학교": "육군",
"육군 제7163부대": "육군",
"육군 제7789부대": "육군",
"육군 종합정비창": "육군",
"육군 항공사령부": "육군",
"육군방공학교": "육군",
"육군종합정비창": "육군",
"육군제7789부대": "육군",
"육군제7163부대": "육군"})


df["군 분류"] = df["발주기관"].map(classification_map).fillna("미분류")

In [100]:
df.to_csv(r"C:/theBoram4Jo/hasun/Total 물품 낙찰 결과_군_분류_추가.csv", 
          index=False, 
          encoding="cp949")

In [106]:
file_path ="C:/theBoram4Jo/hasun/Total 물품 낙찰 결과_군_분류_추가.csv"

In [107]:
df = pd.read_csv(file_path, encoding="cp949")

print(df.shape)
print(df.columns)
df.head()

(74732, 21)
Index(['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관',
       '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)',
       'ss', '낙찰자(연락처).1', '낙찰자(주소)', '낙찰률', ' 낙찰금액 ', '군 분류'],
      dtype='object')

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,...,낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),ss,낙찰자(연락처).1,낙찰자(주소),낙찰률,낙찰금액,군 분류
0,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,2016-12-30 12:30,...,주식회사 전우밀리터리,Jung woo military,이정구,222730487,222730487,02-2273-0487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,"23,689,950",육군
1,1,LFC0043,1,45002,1,장거리 이동 신병 도시락 제조납품,물품,LFC,육군훈련소,2016-12-30 10:00,...,주식회사 엘엔에프 농업회사법인,LNF,이용환,437318109,437318109,043-731-8109,충청북도 옥천군 옥천읍 삼청리877-1,96.8333,"5,810",육군
2,22,LGT0034,1,48136,***,0부대 중대시설 분전반 제조설치(16-312),물품,LGT,제2307부대,2016-12-29 11:00,...,설악테크,seorak tech,김화성,334610399,334610399,033-461-0399,강원특별자치도 인제군 북면 원통로74번길10-5(원통농공단지),88.0408,"29,098,720",육군
3,22,UMM0839,1,48049,***,13-본-국대-01 00학교 가구 및 비품 제조설치,물품,UMM,국군재정관리단,2016-12-29 11:00,...,주식회사 디에스나이키,"DS NAIKI CO.,LTD",김준홍,27342125,27342125,02-734-2125,"서울특별시 구로구 구로중앙로134, 4층(구로동, 리치몰)",88.2297,"2,165,042,000",기타
4,9,LGT0035,1,48138,***,00부대 중대시설 조명기구 제조납품(16-314),물품,LGT,제2307부대,2016-12-29 11:00,...,주식회사 한서,"HANSEO Co.,LTD",이명옥,337462110,337462110,033-746-2110,강원특별자치도 원주시 태장공단길47-0 (태장동),88.3713,"32,424,410",육군

In [138]:
all_keywords = {
    "2종-피복류": [
        "군복","피복","방한","침구","장구","의류","방탄복","군화","모자","양말","티셔츠","속옷","안전화","작업복","전투복","일용품","특수임무피복",
        "군장류","안전모","장갑","비옷","보호복"
    ],
    "2종-병참물자": [
        "비품","기재","취사","냉난방","군악","체육","교육","장구","포장재","실험기구","안전용품","로프","비품류","장비류","기구류",
        "베어링","볼트","너트","와셔","패킹","씰","가스켓","체인","기어","필터","패드","브러시","벨트","휠","스프링","법무","군사경찰",
        "인쇄","군종","공보정훈","항공장구","잠수장구","기류","해상표적",
        "정훈자료","군악기","교육훈련자재","함정전용품","산업안전용품"
    ],
    "2종-화생방물자": [
        "탐지","보호장비","방독면","치료물자","연막","제독제","구조기구","오염표지판","지역장비","독성제거제","작도기재",
        "개인제독제","제독장비","화학탐지기","화학방호복"
    ],
    "2종-통신물자": [
        "전지","배터리","야전선","CCTV","무전기","전화","팩스","라디오","위성TV","전산","네트워크","컴퓨터","휴대용무전기","수신기",
        "군용전화기","교환기","전술통신","네트워크장비"
    ],
    "2종-공병물자": [
        "소방","소화기","위장망","소방피복","소방장구",
        "철조망","방책자재","위장자재"
    ],
    "2종-기타": [
        "군사지도","지도","드론","육도","해도","항공도","소형드론","2kg미만드론"
    ],

    "3종-일반유류": ["경유","휘발유","등유"],
    "3종-항공류": ["제트유","항공유","항공휘발유","AV-GAS"],
    "3종-윤활유": ["엔진오일","기어오일","유압작동오일","압축기오일","그리스","방청유","절삭유","절연유"],
    "3종-화공약품류": ["방청제","세관제","솔벤트","부동액","제초제","정수약품","방역약품","살충제",
        "세정제","소독약","염산","황산","가성소다"
    ],
    "3종-고체연료": ["목재펠릿","연탄","공탄","조개탄","착화탄","고형연료"],
    "3종-가스류": ["LPG","LNG","CNG","아세틸렌","냉매","가스","산소","질소","아르곤"],
    "3종-유류포장재료": ["드럼","드럼통","가스용기"],

    "5종-지상탄약": [
        "소구경탄","직사화기탄","박격포탄","포병탄","지대지유도탄","수류탄","지뢰","연막탄","신호탄","화학탄","폭약","폭파기재",
        "축사기탄","교보재용연막탄"
    ],
    "5종-해상탄약": [
        "함포탄","수중탄","기뢰","폭뢰","함정유도탄","RBOC","DAGAIE","신관","교보재용탄약"
    ],
    "5종-항공탄약": [
        "항공유도탄","투하탄","일반폭탄","확산탄","기관포탄","항공로켓탄","심리전탄","전자전탄","자폭드론"
    ],
    "5종-기타": ["탄피","탄약포장","비축원자재"]
}

def classify_from_pdf(text):
    if pd.isna(text):
        return None
    s = str(text)
    for category, kws in all_keywords.items():
        for kw in kws:
            if kw in s:
                return category
    return None

# 입찰공고명 기준 분류
df["군수품분류"] = df["입찰명"].apply(classify_from_pdf)

In [139]:
df[df["군수품분류"].notna()][["입찰명", "군수품분류"]].head(20)

                              입찰명    군수품분류
3    13-본-국대-01 00학교 가구 및 비품 제조설치  2종-병참물자
6      00부대 체육시설 비품구매(고소작업대 등 9종)  2종-병참물자
7              17년 액화석유가스(LPG) 구매   3종-가스류
8                        군수처 취사연료  2종-병참물자
12          토양정화사업 액화석유가스(LPG) 구매   3종-가스류
17               17년 전산장비 유지보수 용역  2종-통신물자
18              2017년 LPG 구매 (강원)   3종-가스류
19              2017년 LPG 구매 (경기)   3종-가스류
20              2017년 LPG 구매 (전라)   3종-가스류
22               17년 전산장비 유지보수 용역  2종-통신물자
23              2017년 LPG 구매 (강원)   3종-가스류
24              2017년 LPG 구매 (경기)   3종-가스류
25              2017년 LPG 구매 (전라)   3종-가스류
26           긴급 영선보수자재 구매(UPS배터리)  2종-통신물자
33         00부대 복지회관 신축 냉난방기 구매설치  2종-병참물자
52                   인쇄용지8종 제조/구매  2종-병참물자
88                 CCTV(지상전술전자장비)  2종-통신물자
92                  17년 액화석유가스 구매   3종-가스류
93                  17년 액화석유가스 구매   3종-가스류
172         취사기구(신발소독판 등 18품목) 구매  2종-병참물자

In [145]:
df.to_csv(r"C:/theBoram4Jo/hasun/Total 물품 낙찰 결과_군_분류_군수품_2종4종분류_추가.csv", 
          index=False, 
          encoding="cp949")

In [148]:
df = pd.read_csv(r"C:\theBoram4Jo\hasun\Total 물품 낙찰 결과_군_분류_군수품_2종4종분류_추가.csv", encoding="cp949")

rules = {
    '4종': {
        'pick_list': ['목재류','건축용', '아파트', '숙소', '제조설치', '철재', '철근', '철선',
                      '페인트', '시멘트', '보일러', '콘크리트', '아스팔트', '벽돌', '타일', '생활관',
                      '토목', '강관', '신축'],
        'remove_list': ['병원', '의무', '치료']
    },
    '8종': {
        'pick_list': ['병원', '환자', '의무', '외상', '안과', '자극', '신경', '의학',
                      '이비인후과', '치과', '붕대', '외과', '수술', '의료', '병리', '예방약',
                      '방사선장비', '의약품', '치료', '안경제작', '위생'],
        'remove_list': ['신축', '보일러', '제조설치']
    }
}

# 기준이 되는 텍스트 컬럼 (예: 입찰공고명)
target_col = "입찰명"

# 규칙 적용
for 종, rule in rules.items():
    pick_list = rule["pick_list"]
    remove_list = rule["remove_list"]

    # pick 조건
    mask_pick = df[target_col].str.contains("|".join(pick_list), na=False)

    # remove 조건
    mask_remove = df[target_col].str.contains("|".join(remove_list), na=False)

    # 최종 적용: pick O & remove X 인 행만 해당 종으로 지정
    df.loc[mask_pick & ~mask_remove, "군수품분류"] = 종

In [149]:
df = pd.read_csv(r"C:\theBoram4Jo\hasun\Total 물품 낙찰 결과_군_분류_군수품_2종4종분류_추가.csv", encoding="cp949")

 rules = {
     '1종':{
         'pick_list'=  [
    '빙수', '바나나', '우유', '콜라', '과일', '탄산', '음료', '발효', '젤리', '견과', '케이크',
    '케익', '브레드', '짜장', '밥', '허니', '감자', '스낵', '식용', '핫바', '소시지', '어묵',
    '핫도그', '두부', '고기', '떡', '쌈무', '메추리', '순대', '단무지', '우동', '단호박', '샐러드',
    '고구마', '국수', '면', '치즈', '라이스', '스파게티', '사과', '푸딩', '망고', '요거트',
    '콘푸', '마카로니', '돈까스', '소스', '간장', '초콜', '마가렛', '베리', '국', '초코',
    '에너지', '몽쉘', '사이다', '매실', '포도', '식혜', '옥수수', '두유', '요구르트', '복숭아',
    '아이스티', '코코넛', '농축액', '피자', '머핀', '견과류', '부식', '분식', '채류', '김치',
    '쿠키', '미니', '약과', '음식', '쇠고기', '콩나물', '아이스크림', '도시락', '과자', '샌드',
    '양갱', '생수', '후식', '만쥬', '슈크림', '파인애플', '과채', '비타민', '커피', '삼겹',
    '건포도', '삼계탕', '조림', '깻잎', '말랭이', '땅콩', '춧잎', '장아찌', '절임', '양념',
    '시래기', '김자', '미역', '튀김', '명란', '젓갈', '창란', '꼴뚜기', '낙지', '깍두기', '키위',
    '메론', '돼지', '등뼈', '갈비', '해물', '숯불', '닭', '생선', '까스', '너비아니',
    '만두', '동그랑땡', '꼬치', '스테이크', '치킨', '너겟', '새우', '말이', '탕수육', '날치',
    '고기만', '바베큐', '폭립', '청국장', '맛살', '오리', '훈제', '족발', '칵테일', '통조림',
    '육수', '버터', '설탕', '차', '가루', '탕', '액젓', '짬뽕', '육류', '동태', '커틀렛', '토란',
    '오징어', '드레싱', '식초', '찜', '딸기', '식량', '식단', '주스', '토마토', '케첩',
    '시리얼', '쌀', '감자전', '버섯', '오이', '피클', '가자미', '계란', '농산', '수산', '축산',
    '고추', '야채', '햄', '후추', '한식', '쌈장', '깨', '조미', '기름', '샌드위치', '볶음',
    '팝콘', '묵', '육개장', '빵', '미트', '유제품', '황도', '파스타', '주류',
    '채소', '맛술', '연어', '버팔로', '치킨윙', '해쉬', '포테이토', '스팸', '맥주', '라멘',
    '구이', '도너츠', '영양식', '쵸코', '푸실리', '생강', '홍합', '꽃게', '바지락', '정육',
    '원유', '비빔밥', '나물', '카라멜', '죽', '레토르트', '발사믹', '춘장', '다시다', '고로케',
    '곤약', '베이컨', '체다', '어패류', '깐풍기', '가쓰오부시', '교자', '까르보나라', '찌개',
    '찹쌀', '육전', '할라피뇨', '소세지', '아몬드', '차돌', '과즙', '고등어', '곡류', '돈육',
    '오이지', '크로크무슈', '간편식', '애플', '코코아', '스무디', '라떼', '타코야끼', '생크림',
    '우엉', '배맛', '샘표', '대패', '버팔로윙', '부챗살', '옹심이', '갈릭', '크로와상',
    '먹는샘물', '새우깡', '비요뜨', '마들렌', '스프', '급식', '환자식', '특식', '식품',
    '증식', '카페', '가다랑어포', '된장', '천일염', '마요네즈', '엿', '시럽',
    '감귤', '리치', '중식', '전복', '간식', '유자', '패스츄리', '영양', '비스킷'
],
          'remove_list':['용역','기구', '냉동고', '에너지', '장치','제조기', '장비', '압축기', 
                       '오리콘','폐기물', '작업', '공사', '판넬']
}