In [10]:
import pandas as pd

In [11]:
IRP_df = pd.read_csv('C:/한화에어로스페이스/workspaces/Crawling project/my_projcet/방위사업청_국내조달 경쟁 입찰결과_20241031.csv', encoding="cp949")
IRP_df.head()

,입찰공고번호,입찰공고차수,입찰공고명,업무구분명,계약체결형태명,계약체결방법명,낙찰자결정방법명,적격심사여부,공고기관명,공고기관코드,...,개찰시각,개찰결과구분명,최종낙찰금액,최종낙찰율,최종낙찰일자,최종낙찰업체명,최종낙찰업체대표자명,최종낙찰업체담당자명,최종낙찰업체사업자등록번호,최종낙찰업체주소
0,MHD0102,4,상륙기동헬기 조종시뮬레이터 선행연구,용역,총액계약,협상에의한계약(서류),협상,N,방위사업청(운영지원과),1690000,...,14:00:00,개찰완료,28000000.0,93.333,2016-02-11,재단법인 한국군사문제연구원,김형철,NaN,126-82-20298,"경기도 성남시 수정구 위례대로83(창곡동, 국방문화센터)"
1,MHD0130,2,특수작전용 유탄발사기사업 선행연구,용역,총액계약,협상에의한계약(서류),협상,N,방위사업청(운영지원과),1690000,...,14:00:00,개찰완료,71000000.0,95.826,2016-01-06,사단법인 안보경영연구원,전건욱,NaN,120-82-07415,"서울특별시 강남구 언주로527, 10층 (역삼동)"
2,UMM0003,2,00부대 물절약 투자대행사업(WASCO 15-A047),용역,총액계약,협상에의한계약(전자),협상,N,국군재정관리단,ZD00303,...,11:00:00,개찰완료,535467000.0,80.279,2016-01-29,주식회사 도화엔지니어링,손영일,유근영,211-81-08009,서울특별시 강남구 삼성로 438(대치동)
3,UMM0004,2,00부대 물절약 투자대행사업(WASCO 15-A048),물품,총액계약,협상에의한계약(전자),협상,N,국군재정관리단,ZD00303,...,11:00:00,유찰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UMM0860,2,16년 음향 영상장비 유지보수 용역,용역,총액계약,일반경쟁,적격심사제,Y,국군재정관리단,ZD00303,...,11:00:00,개찰완료,396923000.0,86.972,2016-01-05,주식회사 케이원,송관섭,전대석,107-81-54150,"서울특별시 금천구 가산디지털2로14, 14층 1405, 1406호(가산동)"

In [12]:
IRP_df = IRP_df[IRP_df['업무구분명'] != '용역']

In [21]:
IRP_df.head()

,입찰공고번호,입찰공고차수,입찰공고명,업무구분명,계약체결형태명,계약체결방법명,낙찰자결정방법명,적격심사여부,공고기관명,공고기관코드,...,개찰시각,개찰결과구분명,최종낙찰금액,최종낙찰율,최종낙찰일자,최종낙찰업체명,최종낙찰업체대표자명,최종낙찰업체담당자명,최종낙찰업체사업자등록번호,최종낙찰업체주소
3,UMM0004,2,00부대 물절약 투자대행사업(WASCO 15-A048),물품,총액계약,협상에의한계약(전자),협상,N,국군재정관리단,ZD00303,...,11:00:00,유찰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,EGG0109,2,155밀리 모의신관류,물품,총액계약,일반경쟁,적격심사제,Y,방위사업청,1690000,...,14:00:00,유찰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,EGG0109,3,155밀리 모의신관류,물품,총액계약,일반경쟁,적격심사제,Y,방위사업청,1690000,...,14:00:00,유찰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,EGG0109,4,155밀리 모의신관류,물품,총액계약,일반경쟁,적격심사제,Y,방위사업청,1690000,...,14:00:00,순위확정,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,UMM0014,1,스펙트럼용 분석기 구매,물품,총액계약,제한경쟁,적격심사제,Y,국군재정관리단,ZD00303,...,11:00:00,개찰완료,71225000.0,88.021,2016-01-29,미래상사,김정윤,김정윤,301-29-35140,충청북도 청주시 상당구 월평로250번길6-0 (용암동)

In [23]:
file_name = '입찰결과_물품.csv'
IRP_df.to_csv (file_name, index=False, encoding='cp949')