In [2]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [155]:
# #base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
# service_name = 'getDmstcCmpetBidResultList'
# serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
# opengDateBegin  = 20160101         #개찰일자시작
# opengDateEnd    = 20161231         #개찰일자종료
# # bidNm=	                       #입찰명 
# # orntCode=	                       #발주기관코드 
# # g2bPblancNoOdr=	               #G2B공고번호차수
# numOfRows       = 10000	           #페이지당항목수
# pageNo          = 1	               #페이지



# params = f'serviceKey={serviceKey}&opengDateBegin={opengDateBegin}&opengDateEnd={opengDateEnd}&numOfRows={numOfRows}&pageNo={pageNo}'

# url = f'{base_url}{service_name}?{params}'
# url

#### open API 불러오기

In [3]:
base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
service_name = 'getDmstcSuccessBidResult'
serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
opengDateBegin  = 20160101         #개찰일자시작
opengDateEnd    = 20161231         #개찰일자종료
# bidNm=	                       #입찰명 
# orntCode=	                       #발주기관코드 
# g2bPblancNoOdr=	               #G2B공고번호차수
numOfRows       = 10000            #페이지당항목수
pageNo          = 1	               #페이지



params = f'serviceKey={serviceKey}&opengDateBegin={opengDateBegin}&opengDateEnd={opengDateEnd}&numOfRows={numOfRows}&pageNo={pageNo}'

url = f'{base_url}{service_name}?{params}'
url

'http://openapi.d2b.go.kr/openapi/service/BidResultInfoServicegetDmstcSuccessBidResult?serviceKey=8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf&opengDateBegin=20160101&opengDateEnd=20161231&numOfRows=10000&pageNo=1'

#### BeautifulSoup을 이용하여 XML 자료 가져오기

In [4]:
xml = requests.get(f'{base_url}{service_name}', params=params).text
soup = BeautifulSoup(xml, 'xml')
items = soup.find_all('item')
len(items)

10000

##### data 1개 추출 (test)

In [158]:
data = {}
for tag in soup.item.find_all():
    data[tag.name] = tag.text.strip() if tag.text else None
data

{'bidCnt': '81',
 'bidNm': '임시명찰 등 2품목 구매',
 'busiDivs': '물품',
 'dcsNo': '47669',
 'iemNo': '***',
 'opengDt': '201612301230',
 'ornt': '제3283부대',
 'orntCode': 'SFL',
 'pblancNo': 'SFL0160',
 'pblancOdr': '1',
 'tbidAddr': '경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 비110호(동산동, 삼송테크노밸리)',
 'tbidAmount': '23689950',
 'tbidCode': 'H84F8',
 'tbidEname': 'Jung woo military',
 'tbidName': '주식회사 전우밀리터리',
 'tbidRate': '88.0062',
 'tbidRptr': '이정구',
 'tbidTel': '0222730487'}

In [159]:
df = pd.DataFrame([data])
df

,bidCnt,bidNm,busiDivs,dcsNo,iemNo,opengDt,ornt,orntCode,pblancNo,pblancOdr,tbidAddr,tbidAmount,tbidCode,tbidEname,tbidName,tbidRate,tbidRptr,tbidTel
0,81,임시명찰 등 2품목 구매,물품,47669,***,201612301230,제3283부대,SFL,SFL0160,1,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",23689950,H84F8,Jung woo military,주식회사 전우밀리터리,88.0062,이정구,0222730487

In [160]:
df.columns

Index(['bidCnt', 'bidNm', 'busiDivs', 'dcsNo', 'iemNo', 'opengDt', 'ornt',
       'orntCode', 'pblancNo', 'pblancOdr', 'tbidAddr', 'tbidAmount',
       'tbidCode', 'tbidEname', 'tbidName', 'tbidRate', 'tbidRptr', 'tbidTel'],
      dtype='object')

#### columns index명 변경

In [5]:
tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']
list(zip(tag_names, col_names))

[('bidCnt', '참가수'),
 ('pblancNo', '공고번호'),
 ('pblancOdr', '공고차수'),
 ('dcsNo', '판단번호'),
 ('iemNo', '항목번호'),
 ('bidNm', '입찰명'),
 ('busiDivs', '업무구분'),
 ('orntCode', '발주기관코드'),
 ('ornt', '발주기관'),
 ('opengDt', '개찰일시'),
 ('tbidCode', '낙찰자(업체코드)'),
 ('tbidName', '낙찰자(상호)'),
 ('tbidEname', '낙찰자(영문상호)'),
 ('tbidRptr', '낙찰자(대표자)'),
 ('tbidTel', '낙찰자(연락처)'),
 ('tbidAddr', '낙찰자(주소)'),
 ('tbidRate', '낙찰률'),
 ('tbidAmount', '낙찰금액')]

In [6]:
def to_extract_row(item, tag_names, col_names=None):
    data = {}
    if col_names is None:
        col_names = tag_names
    for tag, col in zip(tag_names, col_names):
        tagobj = item.find(tag)
        data[col] = tagobj.text.strip() if tagobj else None
    return data

In [163]:
item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]

In [164]:
df= pd.DataFrame(item_list)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   참가수        10000 non-null  object
 1   공고번호       10000 non-null  object
 2   공고차수       10000 non-null  object
 3   판단번호       10000 non-null  object
 4   항목번호       10000 non-null  object
 5   입찰명        10000 non-null  object
 6   업무구분       10000 non-null  object
 7   발주기관코드     10000 non-null  object
 8   발주기관       10000 non-null  object
 9   개찰일시       10000 non-null  object
 10  낙찰자(업체코드)  10000 non-null  object
 11  낙찰자(상호)    10000 non-null  object
 12  낙찰자(영문상호)  9294 non-null   object
 13  낙찰자(대표자)   10000 non-null  object
 14  낙찰자(연락처)   10000 non-null  object
 15  낙찰자(주소)    10000 non-null  object
 16  낙찰률        10000 non-null  object
 17  낙찰금액       10000 non-null  object
dtypes: object(18)
memory usage: 1.4+ MB

# 자동함수 만들기

In [8]:
def request_estate_data(opengDateBegin  = '20180101',
                        opengDateEnd    = '20181231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [9]:
soup = request_estate_data()
df3 = extract_data_and_DF(soup, tag_names, col_names)
df3

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,5,MHD0081,2,41292,***,우주 무기체계 사업을 위한 계약적 보완 방안 연구,용역,MHD,방위사업청(운영지원과),201812311600,BDDFB,한국항공대학교 산학협력단,korea aerospace university-industry cooperatio...,오현웅,023000390,"경기도 고양시 덕양구 항공대학로76-0 (화전동, 한국항공대학교내)",None,47500000
1,11,MDK0018,1,50439,***,’19년 국방수송정보체계 내 상용소프트웨어 유지보수,용역,MDK,국군수송사령부,201812311100,C0E83,주식회사코드원,"CODEONE Co.,Ltd.",동중영,0432670001,"충청북도 청주시 서원구 사직대로164번길9, 401(사창동)",87.814,40885150
2,2,SDG0059,2,49024,001,19-음식물쓰레기 수거 및 처리용역,용역,SDG,제2002부대,201812311100,E446A,예진농장,yejin,최윤선,0312914238,경기도 수원시 권선구 서수원로594번길163-0 (입북동),99.4273,158
3,3,UMM0833,1,50764,***,18-공군연습용 워게임장비 교체사업 리스,물품,UMM,국군재정관리단,201812311100,H24E1,주식회사 아이비케이캐피탈,IBK Capital Corporation,문창환,025319774,서울특별시 강남구 테헤란로414 (대치동),98.9106,1024535390
4,35,UMM0825,2,48861,***,19년 공군기록관련 전산체계 통합유지보수용역,용역,UMM,국군재정관리단,201812311100,HEA3F,대양종합솔라팅 주식회사,DEAYANG SOLARTING,한선미,0619028600,전라남도 영광군 대마면 전기차1로129-0,87.898,110386510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10384,11,UMM0763,1,49749,***,18년 항공교통관제 CBT 유지보수 용역,용역,UMM,국군재정관리단,201801021100,BB387,한국소프트스페이스주식회사,KSSI,최종필,0220280040,"서울특별시 구로구 디지털로34길 27, 대륭포스트타워 3차 1001호(구로동)",88.1172,61673000
10385,2,SFL0001,1,00241,***,18-교-예비군중대 프린터 렌탈용역,용역,SFL,제3283부대,201801021030,CB20E,포항서비스,pohang service,정창영,0542780002,경상북도 포항시 북구 양덕남로16-1 (장성동),97.9065,14790000
10386,4,UAZ0040,1,50768,***,18-국방어학원 현장학습 버스임차용역,용역,UAZ,합동군사대학교,201801021030,A561E,삼우고속관광(주),samwooexpress,김경자,029427889,서울특별시 동대문구 답십리로 77(),94.8882,19890000
10387,6,HDC0023,1,51143,***,18-무한임대프린터,용역,HDC,공군제1전투비행단,201801021030,D9307,주식회사 광명프라자,None,하윤수,0622613353,광주광역시 북구 서하로 356-1(),88.0527,27395000
10388,2,HDC0022,1,51145,***,18-생활폐기물처리용역,용역,HDC,공군제1전투비행단,201801021030,B6532,초당환경유한회사,chodang environment,박영남,0629441488,전라남도 장성군 삼서면 옥산길9,96.631,50796000

#  df_년도 별로 저장

## 2016

In [167]:
def request_estate_data(opengDateBegin  = '20160101',
                        opengDateEnd    = '20161231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [168]:
soup = request_estate_data()
df_2016 = extract_data_and_DF(soup, tag_names, col_names)
df_2016

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,81,SFL0160,1,47669,***,임시명찰 등 2품목 구매,물품,SFL,제3283부대,201612301230,H84F8,주식회사 전우밀리터리,Jung woo military,이정구,0222730487,"경기도 고양시 덕양구 통일로140, 1층 에이143호, 2층 에이261호,지하1층 ...",88.0062,23689950
1,1,UMM0792,2,41871,***,"17년 직접입영장병 신체검사 용역(경기 연천,파주)",용역,UMM,국군재정관리단,201612301100,D2701,(사)대한결핵협회,knta,신민석,0226339461,서울특별시 서초구 바우뫼로6길57 (우면동),69.8055,45300000
2,3,MDN0001,1,00023,***,'17년 IP교환기 유지보수,용역,MDN,국군화생방방호사령부,201612301100,C980F,씨지에스아이티(주),CGSIT,최규식,0226328730,"서울특별시 금천구 가산디지털1로1-0 (가산동, 더루벤스밸리) 1208호",88.8825,21115480
3,2,UMM0829,1,45191,***,17년 직접입영장병 신체검사 용역(인천 부평등 3개소),용역,UMM,국군재정관리단,201612301100,D2701,(사)대한결핵협회,knta,신민석,0226339461,서울특별시 서초구 바우뫼로6길57 (우면동),74.1187,59572000
4,6,HDC0035,2,47685,***,17년 무한 임대프린터 계약,용역,HDC,공군제1전투비행단,201612301030,D9307,주식회사 광명프라자,None,하윤수,0622613353,광주광역시 북구 서하로 356-1(),90.0891,21980000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10508,3,MCT0031,1,45032,***,2016년 승강기 유지관리용역,용역,MCT,국군체육부대,201601041030,E81B2,청운엘리베이터주식회사,cheoungun E/V,황지성,0544623945,"경상북도 구미시 산동읍 신당1로4길5-4, 506호(이룸프라자2)",88.4676,18404000
10509,4,UAZ0065,1,45350,***,16-국방어학원 승강기 관리용역,용역,UAZ,합동군사대학교,201601041030,CD34A,신한엘리베이터(주),"Shinhan Elevator Co.,Ltd.",김수복,0319174796,경기도 고양시 덕양구 호수로71번길70-0 (토당동),88.0836,10181000
10510,5,LHQ0062,1,45448,***,16년 근무지원단 사업장 생활폐기물 처리 단가 계약,용역,LHQ,제2작전사령부,201601041030,F7AA5,주식회사 그린알앤이,green.co.kr,이근수,0532568272,대구광역시 중구 국채보상로142길33-27 (동인동4가),88.1043,21830964
10511,3,MDK0030,1,45645,***,15-4차 남수단 한빛부대 긴급재보급 항공수송 용역,용역,MDK,국군수송사령부,201601041030,KS05R,선진로지스틱스(주),"Sunjin Logistics Co.,Ltd",정유진,0222259600,"서울특별시 강동구 양재대로 1553, 선진빌딩4층(천호동)",88.3711,27149000
10512,4,SFL0141,1,45865,***,16-교-승강기 관리용역,용역,SFL,제3283부대,201601041030,E49B4,바론엘리베이터 주식회사,"Baron Elevator Co., Ltd",김승기,0544720069,"경상북도 구미시 산동면 신당1로24, 306호(바젤파크시티)",88.9116,16610000

## 2017

In [170]:
def request_estate_data(opengDateBegin  = '20170101',
                        opengDateEnd    = '20171231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [171]:
soup = request_estate_data()
df_2017 = extract_data_and_DF(soup, tag_names, col_names)
df_2017

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,2,HDL0015,1,50495,***,'18년도 무한잉크프린터 임차용역,용역,HDL,공군제16전투비행단,201712291400,H83BD,늑대와여우(현주컴퓨터),Wolf&Fox computer,김성립,054-654-0207,경상북도 예천군 예천읍 군청앞길9-0,96.7369,24750000
1,3,MDN0016,2,49576,***,'18 IP교환기 유지보수 용역,용역,MDN,국군화생방방호사령부,201712291400,BAE92,주식회사 노하우전기통신,None,양창화,027016290,"서울특별시 영등포구 양산로53, 408호(양평동3가, 월드메르디앙비즈센터)",88.4568,18666538
2,5,UMM0759,1,49329,***,18~20년 학군교 전세버스 수송용역(충청),용역,UMM,국군재정관리단,201712291100,D4B55,주식회사 은성고속관광,silverstar,송숙희,042-271-8881,대전광역시 동구 상소동산내로474번길63,88.9222,176100000
3,14,HCQ0048,1,50471,***,'18년 프린터 임차 용역,용역,HCQ,공군제5공중기동비행단,201712291100,G0CB5,전산&오피스 솔루션,Junsan&Office Solution,신주희,051-633-0996,"부산광역시 남구 고동골로40-2, 2층(문현동)",88.0686,27850000
4,5,SEE0056,2,47400,***,18-J-프린터 임차 용역,용역,SEE,제9해병여단,201712291100,H36B4,한올네트웍스,HANALLNETWORKS,김선학,064-711-1191,제주특별자치도 제주시 우정로16길21 (외도일동),91.3998,18500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10244,30,UMM0835,2,45495,***,17년 정보체계 유지보수 용역,용역,UMM,국군재정관리단,201701021100,B28EB,주식회사 케이원,None,손기봉,028535250,"서울특별시 금천구 가산디지털2로14, 14층 1405, 1406호(가산동)",86.0859,856000000
10245,40,MDD0106,1,48961,***,17년 상담콜센터 용역,물품,MDD,국군수도병원,201701021100,E1EA9,유한회사 창해,"chang hae Co., Ltd",류제성,0626118816,광주광역시 광산구 풍영철길로15(콜롬버스월드 302호),88.0195,45799070
10246,8,SFD0190,1,49535,***,17-P-청룡회관 하수처리시설 위탁 관리 용역,용역,SFD,제9227부대,201701021030,BB224,(주)한길엔지니어링,HANGIL ENGINEERING,허재택,0538132889,경상북도 경산시 경안로 245(중방동),88.9092,15481900
10247,10,LHQ0050,2,48073,***,17년 작전사 영내 사업장생활폐기물 처리 단가 계약,용역,LHQ,제2작전사령부,201701021030,C21B6,(주)원효산업,wonho,윤천경,0536530151,대구광역시 달성군 옥포면 반송2길6,88.5985,40763730
10248,15,SCH0355,1,48905,***,냉동꽃게 등 5종,물품,SCH,해군작전사령부,201701021030,BC466,서진유통,SEO JIN,박소선,051-754-9401,부산광역시 수영구 망미동803-32 28/3,88.184,29445000

## 2018

In [172]:
def request_estate_data(opengDateBegin  = '20180101',
                        opengDateEnd    = '20181231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [173]:
soup = request_estate_data()
df_2018 = extract_data_and_DF(soup, tag_names, col_names)
df_2018

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,5,MHD0081,2,41292,***,우주 무기체계 사업을 위한 계약적 보완 방안 연구,용역,MHD,방위사업청(운영지원과),201812311600,BDDFB,한국항공대학교 산학협력단,korea aerospace university-industry cooperatio...,오현웅,023000390,"경기도 고양시 덕양구 항공대학로76-0 (화전동, 한국항공대학교내)",None,47500000
1,11,MDK0018,1,50439,***,’19년 국방수송정보체계 내 상용소프트웨어 유지보수,용역,MDK,국군수송사령부,201812311100,C0E83,주식회사코드원,"CODEONE Co.,Ltd.",동중영,0432670001,"충청북도 청주시 서원구 사직대로164번길9, 401(사창동)",87.814,40885150
2,2,SDG0059,2,49024,001,19-음식물쓰레기 수거 및 처리용역,용역,SDG,제2002부대,201812311100,E446A,예진농장,yejin,최윤선,0312914238,경기도 수원시 권선구 서수원로594번길163-0 (입북동),99.4273,158
3,3,UMM0833,1,50764,***,18-공군연습용 워게임장비 교체사업 리스,물품,UMM,국군재정관리단,201812311100,H24E1,주식회사 아이비케이캐피탈,IBK Capital Corporation,문창환,025319774,서울특별시 강남구 테헤란로414 (대치동),98.9106,1024535390
4,35,UMM0825,2,48861,***,19년 공군기록관련 전산체계 통합유지보수용역,용역,UMM,국군재정관리단,201812311100,HEA3F,대양종합솔라팅 주식회사,DEAYANG SOLARTING,한선미,0619028600,전라남도 영광군 대마면 전기차1로129-0,87.898,110386510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10384,11,UMM0763,1,49749,***,18년 항공교통관제 CBT 유지보수 용역,용역,UMM,국군재정관리단,201801021100,BB387,한국소프트스페이스주식회사,KSSI,최종필,0220280040,"서울특별시 구로구 디지털로34길 27, 대륭포스트타워 3차 1001호(구로동)",88.1172,61673000
10385,2,SFL0001,1,00241,***,18-교-예비군중대 프린터 렌탈용역,용역,SFL,제3283부대,201801021030,CB20E,포항서비스,pohang service,정창영,0542780002,경상북도 포항시 북구 양덕남로16-1 (장성동),97.9065,14790000
10386,4,UAZ0040,1,50768,***,18-국방어학원 현장학습 버스임차용역,용역,UAZ,합동군사대학교,201801021030,A561E,삼우고속관광(주),samwooexpress,김경자,029427889,서울특별시 동대문구 답십리로 77(),94.8882,19890000
10387,6,HDC0023,1,51143,***,18-무한임대프린터,용역,HDC,공군제1전투비행단,201801021030,D9307,주식회사 광명프라자,None,하윤수,0622613353,광주광역시 북구 서하로 356-1(),88.0527,27395000
10388,2,HDC0022,1,51145,***,18-생활폐기물처리용역,용역,HDC,공군제1전투비행단,201801021030,B6532,초당환경유한회사,chodang environment,박영남,0629441488,전라남도 장성군 삼서면 옥산길9,96.631,50796000

## 2019

In [174]:
def request_estate_data(opengDateBegin  = '20190101',
                        opengDateEnd    = '20191231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [175]:
soup = request_estate_data()
df_2019 = extract_data_and_DF(soup, tag_names, col_names)
df_2019

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,4,HDK0050,1,52759,***,광성회관 식자재 육류 구매 계약,물품,HDK,공군제11전투비행단,201912311600,J8A6A,새마음식육점,None,엄경희,053-989-1167,대구광역시 동구 방촌동90-14 K2 공군기지내 새마음회관,88.8089,107150000
1,3,HDK0049,1,53059,***,19-광성회관 식자재(김치류) 구매,물품,HDK,공군제11전투비행단,201912311400,J0FEE,영농조합법인 팔공김치,None,김태종,0539838030,대구광역시 동구 신평로58-3 (신평동),88.185,59890000
2,3,HDL0028,2,51377,***,체력단련장 액화석유가스(LPG) 구매,물품,HDL,공군제16전투비행단,201912311100,EE2E9,(주)에너지프라자 울진충전소(울진지점),energyplaza,김남진,0315316400,경상북도 울진군 울진읍 울진북로331,88.668,31678290
3,4,LHK0038,1,54304,***,20년 렌탈프린터 임차용역,용역,LHK,제2군단,201912311100,HE132,주식회사 아이블럭춘천,IBLOCK,이상철,07048954213,"강원특별자치도 춘천시 국사봉길12-0, 1층 6호 (퇴계동)",88.0065,26280000
4,6,SFD0180,1,54399,***,20-P-임목폐기물 수거·운반 위탁처리 용역,용역,SFD,제9227부대,201912311100,E683F,주식회사 성안기업,SUNG AN,전동재,0549316407,경상북도 성주군 용암면 사곡공단1길 23(),88.2702,36254000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10626,2,LPH0120,1,50927,001,19년 설특식(훈제닭다리) 구매,물품,LPH,제2167부대,201901021030,FE11F,한국유통,hankook wholesale & retail,김광태,010-6257-4809,경기도 고양시 일산서구 대산로106-0 (주엽동)108-1503,99.4203,1463
10627,5,SCN0243,1,48598,***,배추김치 등 3종,물품,SCN,제7001부대,201901021030,HE281,주식회사 진생식품,Jinsaeng Food,홍장환,051-809-1379,부산광역시 부산진구 부전로140번길25-0 (부전동),88.1576,25547650
10628,4,SDF0165,1,49590,***,세탁기 등 2종 구매 설치,물품,SDF,제5738부대,201901021030,GAF5D,헵시바상사,hebsiba sangsa,최승종,010-6248-7950,"경상북도 포항시 남구 지곡로294-0 (지곡동, 효자그린아파트)233-703호",86.9562,14537000
10629,46,SFC0174,1,51297,***,19년 복지시설 물탱크 청소 용역,용역,SFC,제9691부대,201901021030,BF17D,(주)늘푸른코리아,nel pe ren korea,이 옥 순,0316757202,경기도 안성시 보개원삼로55-0 (가사동),88.6632,1394590
10630,10,SCN0247,1,51238,***,'19-00회관 전기안전관리 용역,용역,SCN,제7001부대,201901021030,DB5B5,유한회사 대웅전기안전기술단,daewoong,길수덕,055-605-3230,"경상남도 창원시 마산회원구 봉암공단9길45-0 (봉암동), 3층",88.2561,2038900

## 2020

In [176]:
def request_estate_data(opengDateBegin  = '20200101',
                        opengDateEnd    = '20201231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [177]:
soup = request_estate_data()
df_2020 = extract_data_and_DF(soup, tag_names, col_names)
df_2020

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,7,LKD0039,1,57673,***,21년 렌탈프린터 임차 용역,용역,LKD,제32보병사단,202012311100,G326A,삼성종합전산,Samsung Total Computation,윤석길,042-633-1929,"대전광역시 서구 도안북로93번길20-23 (도안동), 203호",87.806,72996300
1,4,HDF0080,1,57548,***,청나래 작은도서관 위탁운영 용역,용역,HDF,공군 제8전투비행단,202012311100,F07E6,합자회사 나라,naragunsul,황정화,0334415277,강원특별자치도 화천군 하남면 춘화로3346-0,98.39,31810000
2,13,UMM0005,1,00180,***,21년 전세버스 수송용역(21H017-B),용역,UMM,국군재정관리단,202012311100,C5D5E,주식회사 대진고속관광,DAEJIN TOUR,김재식,0555452226,경상남도 창원시 진해구 충장로 235(),87.208,282473000
3,24,UMM0628,1,55878,***,21년 항공교통관제 CBT 유지보수 용역(21J011-I),용역,UMM,국군재정관리단,202012311100,CE0C5,(주) 투데이게이트,"TodayGate Co.,LTD.",김익훈,0221043535,"서울특별시 금천구 디지털로9길32-0 (가산동, 갑을 그레이트밸리) 비동 804호",87.801,60693600
4,4,UMM0607,1,55159,***,(20F179-A)대기오염측정용역(특정물질),용역,UMM,국군재정관리단,202012311100,A03D4,주식회사 상록 엔 바이 로,sangrokenviro,구명조,0557442552,경상남도 진주시 대곡면 진의로696,87.834,119243220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10188,19,SFH0100,1,53477,***,다목적지원시설 공기조화기 제조 설치,물품,SFH,제9196부대,202001021100,B1370,주식회사 리박산업기계,"NIVAK INDUSTRIAL CO.,LTD",김태호,0314342760,경기도 시흥시 엠티브이23로11-1 (정왕동),88.0351,265386495
10189,2,LCP0032,1,54340,***,항공기 유도장비(VOR)외주정비용역,용역,LCP,육군항공사령부,202001021050,G6E56,주식회사 씨엔테크,CNTech,김훈석,07077208157,"경기도 김포시 양촌읍 황금로117, 이젠테크노존 가동 411호",88.0412,25436000
10190,3,LCP0031,1,54337,***,UH-60시뮬레이터(SFTS) 외주정비용역,용역,LCP,육군항공사령부,202001021040,A4E21,주식회사 한국미디어테크,"KOREA MEDIA TECH. CO., LTD.",위용현,0317457200,경기도 용인시 처인구 이동읍 덕성산단2로76번길46-0,86.9027,226870000
10191,3,LCP0033,1,54341,***,항공전술훈련시뮬레이터(SM-RT1K) 외주정비용역,용역,LCP,육군항공사령부,202001021030,A4E21,주식회사 한국미디어테크,"KOREA MEDIA TECH. CO., LTD.",위용현,0317457200,경기도 용인시 처인구 이동읍 덕성산단2로76번길46-0,85.9352,872990000
10192,3,HCF0172,1,53917,***,'20년 한마음회관 식자재 구매(채소류),물품,HCF,공군군수사령부,202001021000,J8A6A,새마음식육점,None,엄경희,053-989-1167,대구광역시 동구 방촌동90-14 K2 공군기지내 새마음회관,88.3747,74450000

## 2021

In [178]:
def request_estate_data(opengDateBegin  = '20210101',
                        opengDateEnd    = '20211231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [179]:
soup = request_estate_data()
df_2021 = extract_data_and_DF(soup, tag_names, col_names)
df_2021

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,651,HCQ0078,1,59750,***,작전통제소 및 생활관 관급자재 통합배선,물품,HCQ,공군제5공중기동비행단,202112311600,GE97F,우림,Woorim,최현숙,0632863466,전북특별자치도 전주시 완산구 마당재3길20-22 (중노송동),88.003,49307580
1,2,SFD0144,1,59571,***,22년 경주지역 음식물폐기물 위탁처리 용역,용역,SFD,제9227부대,202112311100,K5029,주식회사 블루경상,None,선혜진,054-615-0900,"경상북도 포항시 북구 중흥로208-0, 116호(죽도동)",89.406,13240581
2,6,LBB0071,1,57502,001,경축특식 (22년 삼일절) 핫바세트+탄산음료 구매,물품,LBB,육군제7789부대,202112311030,HE335,농업회사법인 행복 주식회사,happycluster,윤영우,0419318090,충청남도 보령시 청소면 청소큰길254-0,88.983,2619
3,3,SCH0168,1,59628,***,22-진 00지역 승강기 유지보수 용역,용역,SCH,해군작전사령부,202112311030,J843F,주식회사 한림엘리베이터,None,서정훈,0552762776,"경상남도 창원시 의창구 소계로12-0, 테크동 301-3호(팔용동, 창원테크노밸리)",88.574,11840400
4,5,SCN0213,1,59858,***,22-진-03 00회관 세탁물 세탁용역,용역,SCN,제7001부대,202112311030,L0089,정우세탁산업,None,조성우,010-8824-0990,경상남도 창원시 의창구 동읍 자여로50-24,88.253,17420634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10117,5,SCN0009,1,00257,***,액화석유가스(LPG)구매,물품,SCN,제7001부대,202101041030,G27FF,진해산소 일사가스,jinhaeox,노진섭,0555465562,경상남도 창원시 진해구 행암동30-4,88.313,15324073
10118,15,SCN0008,1,00256,***,가자미 등 30종,물품,SCN,제7001부대,202101041030,HCC92,아라날,ARANAL,안형준,010-5099-1799,경상남도 창원시 성산구 상남로75-0 (상남동) 505호,88.018,35714420
10119,15,SCN0007,1,00255,***,가스오부시 등 96종,물품,SCN,제7001부대,202101041030,JB275,케어트리,None,박수산,01041441030,경상남도 창원시 마산회원구 3·15대로732-0 (합성동) 4층 4025호,88.053,42571860
10120,15,SCN0006,1,00254,***,가지 등 86종,물품,SCN,제7001부대,202101041030,JB275,케어트리,None,박수산,01041441030,경상남도 창원시 마산회원구 3·15대로732-0 (합성동) 4층 4025호,88.035,72142580
10121,20,SCN0004,1,00232,***,닭고기 등 12종,물품,SCN,제7001부대,202101041030,FEE59,피앤에스,p&s,성기우,01055013502,"경상남도 창원시 성산구 중앙대로37, 519호 -5호(중앙동, 경남오피스텔)",88.013,19336110

## 2022

In [180]:
def request_estate_data(opengDateBegin  = '20220101',
                        opengDateEnd    = '20221231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [181]:
soup = request_estate_data()
df_2022 = extract_data_and_DF(soup, tag_names, col_names)
df_2022

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,7,HDF0064,1,63150,***,23년 음식물쓰레기 처리용역,용역,HDF,공군 제8전투비행단,202212301100,G51F9,아라환경,ara naturao recycie,이석재,0334354471,강원특별자치도 홍천군 홍천읍 영서로1981-0,84.51,139771140
1,3,LHG0107,1,62567,***,12사단 간부숙소150실 신축 관급자재 - 콘크리트 말뚝,물품,LHG,제1862부대,202212301100,J0919,성우파일 주식회사,None,김용길,0437446350,충청북도 영동군 용산면 영동산단로217-0,88.388,39542800
2,152,LKH0030,1,63490,***,117 예비군훈련대 개편(통합배선),물품,LKH,제6128부대,202212301030,A2A13,(주)현진하이테크,hyunjin hi-tech,정금수,05056032222,"광주광역시 광산구 하남울로12번상길13, 4층, 5층(하남동)",87.998,181818531
3,10,SCP0166,2,60665,***,23-체력단련장 식물성 잔재물(예지물)처리 용역,용역,SCP,제8385부대,202212301030,HA3D7,주식회사 엘에스에너지,lsenergy,김학민,0316744885,경기도 안성시 삼죽면 상삼로119,88.052,9201440
4,46,SCQ0197,1,63027,***,"커피머신(2그룹, 설치포함) 구매",물품,SCQ,제9911부대,202212301030,HB4FB,주식회사 양치기소년들,"SHEPHERDBOYS CO., LTD",김보민,031-471-1412,경기도 시흥시 수인로3465번길60-0 (신천동),88.273,4200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10452,15,LGC0062,1,60660,***,22년 사관후보생 이발용역,용역,LGC,육군학생군사학교,202201041030,G5F44,주식회사 티에이치서비스,(주)THservice,황영숙,024945568,서울특별시 금천구 시흥대로97-0 (시흥동) 25동 306호 시흥유통상가,88.052,48440542
10453,2,SCP0183,1,60553,***,22-동 렌탈프린터 임차 용역,용역,SCP,제8385부대,202201041030,CD041,(주)컴퓨터랜드,computer-land,최관순,0335355454,강원특별자치도 동해시 감추로33-0 (천곡동),89.511,17440800
10454,42,UMM0664,1,58365,***,(21F196-I) '22년 부대하역 용역,용역,UMM,국군재정관리단,202201031100,F81A6,주식회사 영원비엠에스,"YOUNG WON BMS CO,. LTD",조남이,028467701,서울특별시 영등포구 도림로61나길4-0 (대림동),88.019,523034160
10455,4,SDF0186,1,60185,***,22-00병원 음식물류 폐기물 처리 용역,용역,SDF,제5738부대,202201031030,E5866,(주)삼호환경,samhoenv,유성백,0542733333,경상북도 포항시북구 죽도동703-5 4층,88.026,7808400
10456,13,MCN0085,1,60244,***,22년 의약품 구매,물품,MCN,국방부근무지원단,202201031030,JEBE6,주식회사 비와이메디팜,None,이상준,0222489850,"서울특별시 동대문구 답십리로66길102-2, 202호(장안동)",88.136,84049900

## 2023

In [182]:
def request_estate_data(opengDateBegin  = '20230101',
                        opengDateEnd    = '20231231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [183]:
soup = request_estate_data()
df_2023 = extract_data_and_DF(soup, tag_names, col_names)
df_2023

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,8,MDD0154,1,59152,***,2024~2025 국군수도병원 승강기 유지관리 용역,용역,MDD,국군수도병원,202312291700,EA4B7,성우승강기(주),sungwooelevator,김구현,025081616,"서울특별시 강남구 봉은사로451, 201호(삼성동, 성우빌딩)",87.795,81990795
1,35,UMM0788,1,59987,***,24-M-하·폐수처리시설 위탁관리 용역,용역,UMM,국군재정관리단,202312291100,D40FE,청해ENV주식회사,CHUNGHAE ENVIRONMENT COMPANY,이병관,0319463695,"경기도 파주시 가나무로143, 3층 (금릉동, 파주메트로프라자1)",87.753,139660216
2,24,HDQ0099,1,63581,***,20비 23-397 백신중계서버 구매설치,물품,HDQ,제20전투비행단,202312291100,CCDF7,이주씨스템(주),"LEEJOO SYSTEM CO., LTD.",이복균,028133361,"서울특별시 영등포구 가마산로90길22, 2층",88.071,26806910
3,2114,HDL0023,1,65620,***,23-11-273 작전조끼 구매,물품,HDL,공군제16전투비행단,202312291100,M03A0,경덕,None,김효덕,010-2291-2379,충청남도 공주시 이인면 고분티로430-5,88,36622164
4,97,SFH0168,1,63606,***,23-B-사무실 신축 관급자재(자동제어),물품,SFH,제9196부대,202312291100,I40FE,베스트 주식회사,"BEST CO., Ltd",남상미,0428223017,대전광역시 유성구 갑동로25번길53-28 (갑동),88.001,81355585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10513,11,LKT0081,1,63595,001,23년 사령부 영내 생활폐기물 처리용역,용역,LKT,제1989부대,202301021530,KE998,주식회사 에너지명성,None,유재명,0626754200,"전라남도 여수시 대통2길63-3, 1층(화장동)",87.931,256540
10514,2,HCS0033,1,61055,***,"'23년 식자재(김치) 계약(장교,토성회관)",물품,HCS,제3훈련비행단,202301021100,1365F,주식회사 삼화식품,"samhwa foods co., ltd",정태성,0558828440,경상남도 하동군 옥종면 옥단로1653-1,89.349,47190000
10515,35,UMM0757,1,50967,***,23-해-미디어 네트워크 편집시스템 유지보수,용역,UMM,국군재정관리단,202301021100,F1E75,(주)이룸시스,"IROOMSYS CO.,LTD",박준호,0226721142,"경기도 광명시 일직로43, 제6층 제비607호(일직동,지아이디씨)",87.77,110207913
10516,1875,UMM0756,1,59800,***,23-공-임대프린터 용역,용역,UMM,국군재정관리단,202301021100,J8D8F,다선,None,김연경,054-554-1427,"경상북도 문경시 흥덕로17 나동 207호 (흥덕동, 대화비둘기연립주택)",87.746,100075784
10517,3,LMQ0007,2,61041,***,22-140) 고강도 콘크리트 파일 제조납품,물품,LMQ,제7297부대,202301021030,LB024,성우산업 주식회사,None,안숙현,0437459974,"경기도 용인시 수지구 동천로17, 403호(동천동)",88.341,31992884

## 2024

In [184]:
def request_estate_data(opengDateBegin  = '20240101',
                        opengDateEnd    = '20241231',
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [185]:
soup = request_estate_data()
df_2024 = extract_data_and_DF(soup, tag_names, col_names)
df_2024

,참가수,공고번호,공고차수,판단번호,항목번호,입찰명,업무구분,발주기관코드,발주기관,개찰일시,낙찰자(업체코드),낙찰자(상호),낙찰자(영문상호),낙찰자(대표자),낙찰자(연락처),낙찰자(주소),낙찰률,낙찰금액
0,2,UAB0105,1,65201,***,'25년 대천콘도 전기안전관리 대행 용역(긴급 재공고),용역,UAB,국군복지단,202412311700,G2D69,(주)중부전기안전관리,joonghujungi annejuan,신순식,0416313395,충청남도 홍성군 홍성읍 의사로72번길30-14,98.961,8743680
1,283,SDQ0127,1,61399,***,"제한기, 유체유동형 등 52종 구매",물품,SDQ,해군제2수리창,202412311330,I293B,영란 주식회사,Young Ran Corportion,김영란,07046491151,경기도 고양시 일산서구 주엽로150-0 (주엽동),88.032,77491280
2,75,HDQ0087,1,63865,***,20비 24-통합간부식당 식자재(가공품),물품,HDQ,제20전투비행단,202412311100,L808E,정연,None,이정숙,01026170850,"경기도 부천시 송내대로73번길46, 7층 H14호(상동, 대양훼미리코아)",83.042,307369716
3,298,LHM0122,1,64183,***,군-위-293 공병대대 탄약고 지붕보수 등 2건(자재구매,물품,LHM,제15보병사단,202412311100,MF511,시너지원주,None,노미애,01048375254,"강원특별자치도 원주시 오성마을길63-25 (단구동, 원주단구 내안애카운티 에듀파크 ...",88.026,26388089
4,5,LHG0064,1,63941,***,'24년 임차사업(식기세척기) 계약,용역,LHG,제1862부대,202412311100,C7B7E,주식회사 누마스타,NUMASTER,정순금,0317678237,경기도 광주시 초월읍 장담길 21-80( ),86.165,385579633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10141,7,SCN0194,1,65581,***,24-진-04 00원 의료 폐기물 처리용역,용역,SCN,제7001부대,202401021030,I7E28,주식회사 청신산업,chungshin co,전미경,0555870340,경상남도 함안군 칠원읍 용산5길29-74,88.621,24242000
10142,987,LMH0052,1,65791,***,24년 복지회관 청소용역(C082),용역,LMH,제7군단,202401021030,JEC13,성우종합관리 주식회사,None,박성우,0557481225,"경상남도 진주시 에나로142, 5층(충무공동, 솔레어빌딩)",88.002,32485600
10143,30,SFN0078,1,65466,***,24-Y-방송시스템 유지보수용역,용역,SFN,연평부대,202401021030,K9BF9,주식회사 준서전력,None,김혜선,0328860520,"인천광역시 옹진군 영흥면 영흥로482-6 ,102호",88.005,28048800
10144,20,SFN0079,1,65483,***,24-Y-통신전자장비 유지보수용역,용역,SFN,연평부대,202401021030,IFBCE,(주)두굿이엔지,None,전미연,0325611324,인천광역시 서구 고산후로121번길25-0 (원당동) 제일프라자 501-3호,88.057,31135320
10145,2,SCN0193,1,65508,***,24-체단장 액화석유가스(LPG) 구매,물품,SCN,제7001부대,202401021030,G27FF,진해산소 일사가스,jinhaeox,노진섭,0555465562,경상남도 창원시 진해구 행암동30-4,88.187,20790450

## df_년도 데이터프레임 -> csv 저장

In [ ]:
def request_estate_data(opengYear,
                        # bidNm=	               
                        # orntCode=	               
                        # g2bPblancNoOdr=	       
                        numOfRows       = '15000', 
                        pageNo          = '1'	       ):
    opengDateBegin = opengDateBegin +'0101'
    opengDateEnd = opengDateEnd+'1231'
    serviceKey = '8bea1c13542aaa1626e136b275cde504cb37de3c3a31d19cd15d7759b330efdf'
    base_url = 'http://openapi.d2b.go.kr/openapi/service/BidResultInfoService'
    service_name = 'getDmstcSuccessBidResult'
    params = 'opengDateBegin=' + opengDateBegin + '&' \
           + 'opengDateEnd=' + opengDateEnd + '&' \
           + 'serviceKey=' + serviceKey + '&' \
           + 'pageNo=' + pageNo + '&' \
           + 'numOfRows=' + numOfRows
    url = f'{base_url}{service_name}?{params}'
    
    xml = requests.get(url).text
    soup = BeautifulSoup(xml, 'xml')
    return soup

tag_names = ['bidCnt','pblancNo','pblancOdr','dcsNo','iemNo','bidNm','busiDivs','orntCode','ornt','opengDt','tbidCode','tbidName','tbidEname','tbidRptr','tbidTel','tbidAddr','tbidRate','tbidAmount']
col_names = ['참가수', '공고번호', '공고차수', '판단번호', '항목번호', '입찰명', '업무구분', '발주기관코드', '발주기관', '개찰일시', '낙찰자(업체코드)', '낙찰자(상호)', '낙찰자(영문상호)', '낙찰자(대표자)', '낙찰자(연락처)', '낙찰자(주소)', '낙찰률', '낙찰금액']

def extract_data_and_DF(soup, tag_names, col_names):
    item_list = [to_extract_row(item_tag, tag_names, col_names) for item_tag in soup.find_all('item')]
    return pd.DataFrame(item_list)

In [186]:
import os
import pandas as pd

# 저장할 폴더 경로
save_path = "C:/한화에어로스페이스/workspaces/Crawling project/my_projcet/입찰정보data"

# 만약 폴더가 없다면 자동으로 생성하는 코드 (추천)
if not os.path.exists(save_path):
    os.makedirs(save_path)

# 각 데이터프레임을 올바른 방법으로 저장
df_2016.to_csv(os.path.join(save_path, '2016년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2017.to_csv(os.path.join(save_path, '2017년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2018.to_csv(os.path.join(save_path, '2018년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2019.to_csv(os.path.join(save_path, '2019년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2020.to_csv(os.path.join(save_path, '2020년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2021.to_csv(os.path.join(save_path, '2021년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2022.to_csv(os.path.join(save_path, '2022년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2023.to_csv(os.path.join(save_path, '2023년 물품 낙찰 결과.csv'), index=False, encoding='cp949')
df_2024.to_csv(os.path.join(save_path, '2024년 물품 낙찰 결과.csv'), index=False, encoding='cp949')

print(f"'{save_path}' 경로에 모든 파일 저장을 완료했습니다! 🎉")

'C:/한화에어로스페이스/workspaces/Crawling project/my_projcet/입찰정보data' 경로에 모든 파일 저장을 완료했습니다! 🎉